### ISSUE TITLE
Add support for switchable indexes

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/bie-index#10]
Allow indexes to be built in a separate core, and add the ability to switch between cores. This will enable indexes to be built and switched over in production without down time.

**Comment by nickdos** [comment]
requires admin interface via Grails app...

**Comment by nickdos** [comment]
@djtfmartin the SOLR admin interface allows us to do this now... were you thinking we should have a button on the bie-index admin page to do this? Or is the SOLR page good enough?

**Comment by djtfmartin** [comment]
I think the SOLR page is good enough. Closing.
