### ISSUE TITLE
Higher taxa with rankID of zero

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#103]
http://bie.ala.org.au/ws/species/urn:lsid:biodiversity.org.au:afd.taxon:ef5515fd-a0a2-4e16-b61a-0f19f8900f76.json

Can be seen on any bird species page - classification tab shows no rank for GNATHOSTOMATA

![image](https://cloud.githubusercontent.com/assets/532845/18075900/6dc95010-6ebc-11e6-8023-c69899408499.png)

**Comment by nickdos** [comment]
Might be an AFD issue as they specify the rank as `Higher Taxon (taxsupragen)`:

https://biodiversity.org.au/afd.taxon/ef5515fd-a0a2-4e16-b61a-0f19f8900f76.html

**Comment by charvolant** [comment]
GNATHOSTOMATA from AFD is supplied as taxon.rank.H which means generic higher-order taxon. We could label these as being such but they effectively have a rank of "anywhere"

**Comment by adam-collins** [comment]
Appears fixed.
