### ISSUE TITLE
Species group addition

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#104]
Email from user:

> Hi ALA people,
> Can you please adjust your species categories to include woodlice Crustacea, Isopoda (I had to submit it in the Crab & Lobster subgroup).
> Also there is no category for worms and leeches etc. Annelida, Hirudinea or Oligochaeta etc. I had to a submit a record of a local Striped Forest Leech (Chtonobdella limbata) as a Fish & Carpet Shark! (otherwise the submission was not accepted).
> Also, I couldn't find a category for slime moulds etc. (Protista) either.
> I intend to edit submissions when you have updated these groupings.
> Many thanks
> Keep up the great work.
> Terry Annable

**Comment by adam-collins** [comment]
moved to #276
