### ISSUE TITLE
BIE species download broken?

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/bie-index#107]
http://bie.ala.org.au/ws/download?fields=guid,parentGuid,kingdom,phylum,class,bioOrder,family,genus,scientificName&q=family:Fabaceae

and

http://bie.ala.org.au/ws/download?q=family%3ASPHENISCIDAE&fields=guid%2Crk_genus%2CnameComplete%2Crank

are both giving 500 errors ...

**Comment by djtfmartin** [comment]
The indexed field is now rk_family.
On the upside, we support lots of different ranks now not just the major linnaean ones.

**Comment by raymondben** [comment]
OK, whoops, sorry, I missed that on the q=parameter. (PS, the api.ala.org.au page needs updating: my first example is from there)

Now, different issue: regardless of what fields I ask for, it returns taxonID,taxonRank,scientificName,establishmentMeans,genus,family,order,class,phylum,kingdom,datasetName

e.g. http://bie.ala.org.au/ws/download?fields=bilbobaggins&q=rk_family:Fabaceae

**Comment by raymondben** [comment]
Thanks!
