### ISSUE TITLE
Bulk species lookup - does the vernacular flag do anything?

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/bie-index#109]
http://bie.ala.org.au/ws/species/lookup/bulk
Searching e.g. "kookaburra" with vernacular=TRUE returns Dacelo (Dacelo) novaeguineae (as expected), but I get the same result when searching with vernacular=FALSE. Searching for "Dacelo" returns genus Dacelo, regardless of vernacular flag setting.

**Comment by adam-collins** [comment]
https://bie-ws.ala.org.au/ws/openapi#/bulk/Bulk%20species%20lookup%20-%20revised%20JSON%20input%20

`vernacular=true` will include common name search results.
