### ISSUE TITLE
Search queryTitle not recognising quoted GUIDs

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#111]
2 searches, with and without quotes around the GUID (which has internal colons) return same result set but show different `queryTitle` values:

http://bie.ala.org.au/ws/search?q=rkid_phylum:urn:lsid:biodiversity.org.au:afd.taxon:4fb59020-e4a8-4973-adca-a4f662c4645c

-> `queryTitle: "phylum MOLLUSCA"`

http://bie.ala.org.au/ws/search?q=rkid_phylum:%22urn:lsid:biodiversity.org.au:afd.taxon:4fb59020-e4a8-4973-adca-a4f662c4645c%22

-> `queryTitle: "rkid_phylum:"urn:lsid:biodiversity.org.au:afd.taxon:4fb59020-e4a8-4973-adca-a4f662c4645c""`

The second search should also show "phylum MOLLUSCA"

**Comment by adam-collins** [comment]
`queryTitle` is still incorrect when double quotes are used e.g. https://bie.ala.org.au/ws/search?q=rkid_phylum:%22https://biodiversity.org.au/afd/taxa/065f1da4-53cd-40b8-a396-80fa5c74dedd%22
