### ISSUE TITLE
Incorrect images on species page (bad name match)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#116]
> From: "Newman, Peggy (NCMI, Black Mountain)" Peggy.Newman@csiro.au
> Date: Wednesday, 5 October 2016 at 6:20 PM
> 
> Ken Walker ​asked me today about bees in the BIE. 
> 
> When you search (web front end) on this bee name, Hylaeinae ​, you get a single result back that links to this subfamily page:
> 
> http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:e926e880-bdfa-4d18-a16f-93b1695ed4d3
> 
> and it has a picture of a Hawaiian moth at the top of it.  The picture is from a DigiVol record with scientific name Hyles wilsoni wilsoni.  The name match for the moth has came back with Hylaeus (Prosopisteron) wilsoni, which is an Australian bee. Close but no cigar. 
> 
> What should happen here so that the bee subfamily doesn't show up with a pic of a moth? 

Both the overview image and images in gallery are showing moth records. The name on those records has an exact match in the BIE:

http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:b4c4434c-0afb-4959-bdea-3d42b6795acc

So Im not sure why the images are appearing on the Bee subfamily page. It might be a case of a fuzzy match getting a higher score than the exact match due to the subgenus name (in brackets) for the Moth scientific name - `Hylaeus (Prosopisteron) wilsoni`.

**Comment by adam-collins** [comment]
Image filtering has changed since this issue. I do not see moths in the images so I expect it is now working.
