### ISSUE TITLE
Duplicate higher taxa (NZ & AU)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#118]
On 11/10/2016, 8:51 AM, "Ben Raymond" <antarcticben@gmail.com> wrote:
>Hi all
A slight names oddity - not a bug, per se, but something that may be
confusing to users. I'm not sure how best to deal with it, maybe you
have a suggestion?

>In the ALA4R docs I have an example of plotting a taxonomic tree, for
which I start by doing a species search on "penguins" to get the
scientific family name (http://bie.ala.org.au/ws/search.json?q=penguins).

>This returns two family-level names: "Spheniscidae" and "SPHENISCIDAE".
The former is from the New Zealand Organism Register and is a list of
extinct species. The latter is ours (Australian Faunal Directory) and
being extant taxa is the one I (and most users, presumably) would want.
Apart from the upper/lower case, the names are obviously identical. What
would be the best way to restrict the search to *current* taxa? I note
that SPHENISCIDAE (the fossils one) doesn't have a a taxonConceptID, but
I wonder if this reflects its NZ origin rather than the fact that it
refers to extinct taxa.

>And, related to the same query, I notice that
http://bie.ala.org.au/ws/download?q=Spheniscidae returns both
Spheniscidae and SPHENISCIDAE (i.e. this form of search is not
case-sensitive) but the
http://bie.ala.org.au/ws/download?q=rk_family%3ASpheniscidae form is
case sensitive. I assume this is deliberate, but just wanted to check.

>Thanks!
B

**Comment by charvolant** [comment]
There's a complication in the AFD data where Spheniscidae appears twice, once as an accepted taxon

"urn:lsid:biodiversity.org.au:afd.taxon:6dbdebb8-dd70-47ad-a8f4-f70e647717d4","urn:lsid:biodiversity.org.au:afd.taxon:7564dbad-6925-4f15-9ce0-640d6f6fe1e9","","dr2699","SPHENISCIDAE","Bonaparte, 1831","family","urn:lsid:biodiversity.org.au:afd.taxon:6dbdebb8-dd70-47ad-a8f4-f70e647717d4","urn:lsid:biodiversity.org.au:afd.name:277893","accepted","","","","Brodkorb, P. 1963, \"Catalogue of fossil birds. Part 1 (Archaeopterygiformes through Ardeiformes).\", Bulletin of the Florida State Museum. Biological Sciences, vol. 7, pp. 179-293","1963","","","http://biodiversity.org.au/afd.taxon/6dbdebb8-dd70-47ad-a8f4-f70e647717d4","ANIMALIA","urn:lsid:biodiversity.org.au:afd.taxon:4647863b-760d-4b59-aaa1-502c8cdf8d3c"

and once as an almost identical synonym

"urn:lsid:biodiversity.org.au:afd.name:614307","","urn:lsid:biodiversity.org.au:afd.taxon:6dbdebb8-dd70-47ad-a8f4-f70e647717d4","dr2699","Spheniscidae","Bonaparte, C.L., 1831","family","urn:lsid:biodiversity.org.au:afd.taxon:6dbdebb8-dd70-47ad-a8f4-f70e647717d4","urn:lsid:biodiversity.org.au:afd.name:614307","synonym","original spelling","","","Bonaparte, C.L. 1831, \"Saggio di una distribuzione metodica degli animali vertebrati\", Giornale Arcadico di Scienze Lettere ed Arti, vol. 49, pp. 3-77","1831","","","http://:biodiversity.org.au/afd.name/614307","ANIMALIA","urn:lsid:biodiversity.org.au:afd.taxon:4647863b-760d-4b59-aaa1-502c8cdf8d3c

This makes matching the (authorless) NZOR supplied name, um, a challenge. Thinking ...

**Comment by charvolant** [comment]
Restructured the NZOR processing to weed out self-synonyms when building the lookup table of previous taxa.

The following conversation took place:

"Do the New Zealanders not believe in penguins?"
"No, the problem is that the AFD believes in penguins too much"

This correction will go through with the next edition of name lists. In the meantime, AFD gets priority during matching so most penguins get matched to the AFD branch. Some fossil penguins get matched to the NZ branch.
