### ISSUE TITLE
Index species-list pages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#120]
There is an admin function to index specieslist items but it appears to only add list meta-data to existing taxon entries in the form of: "lists for this taxon" and "conservation status".

This issue is to index all "public" lists as top level items in their own right (like regions and collections, etc). The title and description fields should indexed and possibly some of the list attributes could be included (such as `authoritative`, `invasive`, `invasive` etc.

**Comment by adam-collins** [comment]
Limit indexing to authoritative lists.

**Comment by adam-collins** [comment]
It appears I missed that these are included as idxtype:DATARESOURCE, although with far less information. Continuing for now.
