### ISSUE TITLE
Online image re-link not working

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#121]
Attempting to reload the images using the online index is not working. 

The log gets as far as "Loading ..." and then nothing happens.

This is fairly low priority, as we can always rebuild the index in the offline area but stops us from adding to the preferred image list and rebuilding. Also, Patricia's enhancements should make this unnecessary. It's still a buglet.

**Comment by adam-collins** [comment]
no longer an issue
