### ISSUE TITLE
Typo in names data label: "miscellanenous literature"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#123]
There is a data type labelled as "miscellanenous literature", which should be spelt as "miscellaneous literature". An example can be seen here:

http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.name:642215

in both the header area and the names tab.

**Comment by charvolant** [comment]
Fixed in https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/61
