### ISSUE TITLE
Dingo page improvements

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#124]
We currently display a dedicated Dingo page but also follow AFD's ruling that Dingo is just _Canis Familiaris_. The 2 pages are not linked to each other and contradict each other somewhat. Furthermore, the Dingo page has imported description about the Wolf, which should not appear on the ALA.

Suggest we add link from http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.name:642215 to http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:c2056f1b-fcde-45b9-904b-1cab280368d1 in the `Names` tab under Synonyms (ALA source ?).

We need to review how we display these "Miscellaneous literate" documents, as they look like regular species pages.

MartinJ wrote on 2017-01-17:
>I think removing the Canis lupus dingo page completely would cause more confusion.
>Our website WetlandInfo links to ALA species via scientific name, and assumes that ALA has a page for every species in our database (WildNet). e.g.:
https://wetlandinfo.ehp.qld.gov.au/wetlands/ecology/components/species/?canis-lupus-dingo
links to:
http://bie.ala.org.au/species/CANIS+LUPUS+DINGO
>If you remove the page completely then the link to ALA would just be broken and users would miss out on the information from ALA.
>Instead, I'd suggest you ensure the http://bie.ala.org.au/species/CANIS+LUPUS+DINGO forwards to the correct page http://bie.ala.org.au/species/CANIS+FAMILIARIS and there is an explanation on the latter about the change in classification.

**Comment by nickdos** [comment]
More details from Martin:

>Hi Nick,
 
>I'm not sure how feasible it is for you to customise individual pages, but I'd be putting this discussion right at the very top of the overview page. Currently there are two "Description" boxes under the Canis familiaris page, and both talk exclusively of grey wolves, which is very confusing considering it is meant to be an atlas of Australian fauna. The photos are of dingoes, and the right column consists of a mix of information about dingoes and common/wild dogs. I doubt anyone would visit that page and not be utterly confused, and very few would think to click on the Names tab to have the mystery explained.
 
>My role at DEHP is really only technical/programming and IT related so how the URLs link up to our information is my primary concern. If you'd like to discuss in more depth how the information on dingoes/dogs should be structured I could probably get one of the scientists here involved in the discussion.
 
>Thanks again for your engagement on this issue.
 
>Cheers
Martin

**Comment by adam-collins** [comment]
I do not think this is relevant anymore.
