### ISSUE TITLE
Duplicate taxa due to APC vs APNI entries

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#125]
https://bie.ala.org.au/search?q=Asystasia+australasica

First 2 results have the same name & authorship, one from APC and the other from APNI. Should be a single taxon entry in BIE.

**Comment by nickdos** [comment]
Anne sent through this observation:

>I have just had a quick look in APNI and APC. There are 2 usages of the name Asystasia australasica in APNI. A Œvalid¹ name https://id.biodiversity.org.au/name/apni/109506 ‹> the name accepted for APC; and an Œisonym¹ https://id.biodiversity.org.au/name/apni/5991978.
    
>The isonym should not be used for matching purposes.

**Comment by adam-collins** [comment]
Data has changed.
