### ISSUE TITLE
Avoid duplicate common names due to case differences

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#126]
There `common_name` index appears to have duplicate entries for the same name, with the only difference being case sensitive. It doesn't make sense to present the user with 2 entries that look the same, so I suggest we only add new common names, when the name contains diffferent text (case insensitive).

E.g. http://bie.ala.org.au/ws/search?q=Barramundi&start=0&rows=10 hgas these entries which are effectively duplicates:

```
 {
    "id": "46109e5f-8058-4026-85c2-a125ef7f5d35",
    "guid": "46109e5f-8058-4026-85c2-a125ef7f5d35",
    "linkIdentifier": null,
    "idxtype": "COMMON",
    "name": "barramundi",
    "description": null,
    "taxonGuid": "urn:lsid:biodiversity.org.au:afd.taxon:fd0e9dbd-c8ba-4d8d-a9e1-0640f7d8d89f",
    "highlight": "<b>barramundi<\/b>"
  },
  {
    "id": "58428144-55cd-447a-835e-6ced084008be",
    "guid": "58428144-55cd-447a-835e-6ced084008be",
    "linkIdentifier": null,
    "idxtype": "COMMON",
    "name": "Barramundi",
    "description": null,
    "taxonGuid": "urn:lsid:biodiversity.org.au:afd.taxon:fd0e9dbd-c8ba-4d8d-a9e1-0640f7d8d89f",
    "highlight": "<b>Barramundi<\/b>"
  }
```

**Comment by charvolant** [comment]
My instinct is to do this in bie-index, rather than try and process out the common names beforehand.

**Comment by adam-collins** [comment]
Appears resolved.
