### ISSUE TITLE
Incorrect matching with /species

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/bie-index#128]
http://bie.ala.org.au/ws/species/acacia%20dealbata is not matching the correct match http://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2903532

See:
https://github.com/AtlasOfLivingAustralia/biocache-service/issues/115
https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/216

**Comment by nickdos** [comment]
This looks to be fixed in test site with a recent re-indexing:

http://bie-b4.ala.org.au/ws/species/acacia%20dealbata

redirects to http://id.biodiversity.org.au/node/apni/2903532 version
