### ISSUE TITLE
Handling of synonyms

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#13]
Idiocentrus http://biodiversity.org.au/afd.name/580984.html is a synonym of Paranaphoidea http://biodiversity.org.au/afd.name/284691.html

If I enter a query such as `http://bie-dev.ala.org.au/bie-index/search?q=Idiocentrus` I get the response

```
{
    "searchResults":  {
      "totalRecords": 2,
      "facetResults": [ ],
      "results":  [
        {
           "guid": "urn:lsid:biodiversity.org.au:afd.name:580984",
           "idxType": "TAXON",
           "name": "Idiocentrus",
           "kingdom": null,
           "scientificName": "Idiocentrus",
           "author": "Gahan, 1927",
           "nameComplete": "Idiocentrus Gahan, 1927",
           "parentGuid": null,
           "rank": "genus",
           "rankID": 6000,
           "commonName": "",
           "commonNameSingle": ""
    },
      {
            "guid": "urn:lsid:biodiversity.org.au:afd.name:284691",
            "idxType": "TAXON",
            "name": "Idiocentrus Gahan, 1927",
             "kingdom": null,
             "scientificName": "Idiocentrus Gahan, 1927",
              "author": null,
              "nameComplete": "Idiocentrus Gahan, 1927",
              "parentGuid": null,
              "rank": "Genus",
              "rankID": 6000,
              "commonName": "",
              "commonNameSingle": "",
              "acceptedConceptID": "urn:lsid:biodiversity.org.au:afd.name:284691"
        }
    ]
 }
}
```

The entry for Idiocentrus in taxon.csv is

"urn:lsid:biodiversity.org.au:afd.name:580984","","urn:lsid:biodiversity.org.au:afd.name:284691","drXXX","Idiocentrus","Gahan, 1927","Genus","urn:lsid:biodiversity.org.au:afd.taxon:670f5cbd-5a16-4b24-b6cc-aba274ffb930","synonym","synonym","","Family"

and for Paranaphoidea

"urn:lsid:biodiversity.org.au:afd.name:284691","urn:lsid:biodiversity.org.au:afd.name:255026","","drXXX","Paranaphoidea","Girault, 1913","Genus","urn:lsid:biodiversity.org.au:afd.taxon:670f5cbd-5a16-4b24-b6cc-aba274ffb930","accepted","","","Family"

The first response seems to be a free-floating reference to Idiocentrus. The second response points towards the accepted taxon with the Author attached to the name. 

Is this the correct response?

**Comment by adam-collins** [comment]
I think this is fine today. The first response is the `accepted`, the second is `synonym`
