### ISSUE TITLE
Hibbertia puberula subsp. glabrescens (EPBC): >1,800 records mis-matched to this name

### ISSUE THREAD

**Issue by ryonen** [AtlasOfLivingAustralia/bie-index#132]
Hibbertia puberula subsp. glabrescens is an EPBC-listed taxon (Critically Endangered) restricted to the Bankstown area of NSW: http://www.environment.gov.au/cgi-bin/sprat/public/publicspecies.pl?taxon_id=86645

AVH and ALA searches on this name return >1,800 Hibbertia records (all submitted as "sp." or with "interesting" epithets etc.) from across Australia: http://avh.ala.org.au/occurrences/search?taxa=Hibbertia%20puberula%20subsp.%20glabrescens#tab_mapView 

Prior to Doug's good work in the names indexing, we established a clear pattern across plant groups where records submitted as Genus "sp." were being attributed to the phrase-name with the lowest alphabetical ranking (e.g. Tephrosia sp. became Tephrosia sp. Adels Creek; Synaphea sp. became Synaphea sp. Argyle, etc.). I seem to recall that the previous phrase name for this Hibbertia (described in 2012) was Hibbertia sp. Bankstown, and that the records were being incorrectly matched to this because "B". This doesn't seem to have resolved itself with the new indexing.

Hibbertia puberula subsp. glabrescens is on APNI and is APC-checked: https://biodiversity.org.au/nsl/services/search?product=APNI&tree.id=3029293&name=Hibbertia+puberula+subsp.+glabrescens+Toelken&inc._scientific=&inc.scientific=on&inc._cultivar=&inc._other=&max=100&display=apni&search=true

No idea whether this is a widespread problem.

**Comment by adam-collins** [comment]
Only 7 matches today. Treating as fixed.
