### ISSUE TITLE
Subgenus (or synonymous genus) in taxon name wreaks havoc with name search

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/bie-index#133]
For species that have a subgenus (or synonymous) name in parentheses in their accepted name, the first match returned by a search lacking that parenthetic text is (I believe) incorrect. 

For example, [a search for _Cinclosoma castanotum_](http://bie.ala.org.au/search?q=Cinclosoma+castanotum) returns _Cinclosoma castanotum clarum_ as its first match, while the correct taxon, _Cinclosoma (Malleeavis) castanotum Gould, 1840_, is the 4th match. 

This is particularly problematic when using APIs, e.g. `ALA4R::search_names`, which returns the first match. 

I wonder if it would be sensible to ignore text in parentheses when searching ... or would that cause other problems?

**Comment by adam-collins** [comment]
Now we have the name matching service that returns the expected result https://namematching-ws.ala.org.au/api/search?q=Cinclosoma%20castanotum
