### ISSUE TITLE
Self-named taxa create StringIndexOutOfRange exception on import when trying to build formatted name

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#135]
Eg. *Karlingia chitinophila* Karling

Naughty, naughty but author search should be from the right of the name and zero index should be accommodated in ImportService.buildFormattedName

**Comment by adam-collins** [comment]
It appears to have loaded now https://bie.ala.org.au/species/Karlingia%20chitinophila%20Karling
