### ISSUE TITLE
Incorrect behaviour when filtering records by a field that may be an empty string

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/bie-index#136]
At http://biocache.ala.org.au/occurrences/search?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:60221177-d785-44e5-9adb-a7914a148e3f&fq=#tab_mapView, subsetting country to "Australia" and "" (empty string), does not behave as expected. The corresponding search results url is http://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A60221177-d785-44e5-9adb-a7914a148e3f&fq=(country%3A%22Australia%22%20OR%20-country%3A*)#tab_mapView.

Maybe this is because the service uses `-country:*` to select empty string, and this conflicts with `country:Australia`?

![image](https://cloud.githubusercontent.com/assets/818438/24846729/cea9f0a4-1dff-11e7-9bbb-f43837478cda.png)

**Comment by adam-collins** [comment]
This was a SOLR search issue that was resolved by changing the query. Fixed in [biocache-hubs](https://github.com/AtlasOfLivingAustralia/biocache-hubs)
