### ISSUE TITLE
Incorrect imageId being set for image

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#138]
Genus `Austrogorytes `: http://bie.ala.org.au/ws/species/urn:lsid:biodiversity.org.au:afd.taxon:c8feabb9-03c7-4f87-afad-e4d21a2fbdde

has:

`imageIdentifier: "90d7ddd8-6af5-40e7-86c4-5178c537e769",`

However this image is for a different genus (no synonyms are indicated). There is NO entry in the list tool (http://lists.ala.org.au/speciesListItem/list/dr4778) either.

Looks like a bug or bad lookup is matching this taxon to the image.

**Comment by adam-collins** [comment]
Different image today and there was work this year for image setting.

**Comment by jhpoelen** [comment]
@adam-collins appreciating your rigor in reviewing older issues!
