### ISSUE TITLE
Common name search issue (with autocomplete)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#139]
http://bie.ala.org.au/ws/auto?q=eastern+grey+kangaroo (and
http://bie.ala.org.au/ws/auto?q=red+kangaroo)

does **not** show _Macropus giganteus_ in the results list. Furthermore, 

http://bie.ala.org.au/search?q=eastern+grey

shows the common name result but the proper species page (_Macropus giganteus_) is **not** on the first page of results. I think this is related to why the autocomplete search is not working - the common name is not being associated with the "taxon" doc in SOLR, possibly(?).

**Comment by nickdos** [comment]
Confirmed this is likely explanation. E.g. http://bie.ala.org.au/ws/search?q=Macropus%20giganteus

shows "Macropus giganteus" has empty common name fields...

```
commonName: "",
commonNameSingle: "",
```

**Comment by charvolant** [comment]
Confirmed 

urn:lsid:biodiversity.org.au:afd.taxon:23f4784e-1116-482c-8e3e-b6b12733f588","urn:lsid:biodiversity.org.au:afd.name:395390","dr2699","Eastern Grey Kangaroo","common","en-AU","http://biodiversity.org.au/afd.name/395390"

is in the vernacularNames.csv file

**Comment by charvolant** [comment]
Culprit is a line that removes any common name without a language of 'en' exactly. https://github.com/AtlasOfLivingAustralia/bie-index/blob/master/grails-app/services/au/org/ala/bie/ImportService.groovy#L1847  Changing to make configurable,

**Comment by charvolant** [comment]
Made accepted languages for common names configurable. The default accepts any language. A comma-separated list of acceptable languages can be configured via `autoComplete.languages` eg. `autoComplete.languages=en,en-AU,en-NZ`
