### ISSUE TITLE
Handling of exclusions and misapplied names

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#14]
Excluded names and misapplications should indicate taxonomic status.
# Exclusions

_Carbo ater_ http://biodiversity.org.au/afd.name/258782.html is excluded in two ways. It's an excluded name at the level of class Aves and it's also an excluded synonym of the subgenus Phalacrocorax (Phalacrocorax) http://biodiversity.org.au/afd.name/456732.html

A query of `${baseUrl}/search?q=Carbo+ater` with return results at both levels with no indication of excluded status, as well as the accepted names. The accepted names do not list _Carbo ater_ as a synonym (which is probably a good thing).

Data from taxon.csv:

"urn:lsid:biodiversity.org.au:afd.name:258782","","urn:lsid:biodiversity.org.au:afd.name:242262","drXXX","Carbo ater","Lesson, 1831","Class","urn:lsid:biodiversity.org.au:afd.taxon:5ed80139-31bb-48a8-9f57-42d8015dacbb","excluded","","",""
"urn:lsid:biodiversity.org.au:afd.name:258782","","urn:lsid:biodiversity.org.au:afd.name:456732","drXXX","Carbo ater","Lesson, 1831","Subgenus","urn:lsid:biodiversity.org.au:afd.taxon:faa3f032-395c-4301-8f9a-b618b192b90c","excluded","","","Genus"
# Misapplied

Misapplied names also have no indication of status
## Easy

`${baseUrl}search?q=Limosina+mediospina` returns the same sort of results as the excluded query, with the pointer to the accepted concept first. This should work fine.

Data from taxon.csv

"urn:lsid:biodiversity.org.au:afd.name:538645","","urn:lsid:biodiversity.org.au:afd.name:539015","drXXX","Limosina mediospina","","Species","urn:lsid:biodiversity.org.au:afd.taxon:01983c25-20d8-4462-b06f-cfcba9a2b169","misapplied","","","Genus"
## Hard

`http://bie-dev.ala.org.au/bie-index/search?q=Chelmonops+truncatus` returns a misapplication to _Chelmonops curiosus_ and an accepted taxon. 

Data from taxon.csv

"urn:lsid:biodiversity.org.au:afd.name:375909","urn:lsid:biodiversity.org.au:afd.name:258929","","drXXX","Chelmonops truncatus","Kner, 1859","Species","urn:lsid:biodiversity.org.au:afd.taxon:17f735cd-883a-4632-bd55-f8a24fd4a916","accepted","","","Genus"
"urn:lsid:biodiversity.org.au:afd.name:375909","","urn:lsid:biodiversity.org.au:afd.name:357623","drXXX","Chelmonops truncatus","Kner, 1859","Species","urn:lsid:biodiversity.org.au:afd.taxon:bd058cad-e107-405d-bdb6-3454d51e0d20","misapplied","","","Genus"

**Comment by charvolant** [comment]
Niels points out that misapplied is a taxonomicStatus and exlcuded is an occurrenceStatus

**Comment by adam-collins** [comment]
Status is in the response so I guess all is well here.
