### ISSUE TITLE
Missing extantStatuses values in SOLR

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#141]
@raymondben pointed out that he is getting a few extinct NZ species being returned in search/download requests to BIE and he is not able to filter them as the `extandStatuses` values are empty. See http://bie.ala.org.au/ws/species/NZOR-4-19240.json. Ben notes that AFD species also have blank values (but are listed as extinct in AFD), so looks like a code vs data issue...

Would also be worth checking if we are indexing this data, as it would be useful to be able to filter out extinct species from results.

**Comment by adam-collins** [comment]
Issue is out of date. I cannot find anything `extand` or `extinct`. Autocomplete species searches via the biocache-service can limit results to those that have an occurrence.
