### ISSUE TITLE
Taxon JSON doc fails when & char is in path

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#142]
E.g. http://bie.ala.org.au/ws/taxon/ALA_Caesia_sp._Koolanooka_Hills_(R._Meissner_&_Y._Caruso_78)

throws a 500 error, as does:

http://bie.ala.org.au/ws/taxon/ALA_Caesia_sp._Koolanooka_Hills_(R._Meissner_%26_Y._Caruso_78)

which is correctly encoded.

Search to show the info in index:

http://bie.ala.org.au/ws/search?q=ALA_Caesia_sp._Koolanooka_Hills

shows `id: "e63f6fbb-b304-449c-9319-e839230ee25a", guid: "ALA_Caesia_sp._Koolanooka_Hills_(R._Meissner_&_Y._Caruso_78)"`

See https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/69

**Comment by charvolant** [comment]
These are special taxonIDs minted for species that need a taxon but don't appear in any of the name lists. Usually a result of something like a conservation list having a name. These appear in pre-processing and can be changed to either get rid of annoying punctuation or simply replaced by a UUID.

**Comment by nickdos** [comment]
That example is actually a valid name that is fairly new so hasn't been added to APNI yet but is on a WA list already. So wee need to match to it for occurrence record searches.

Also other ALA_* names work so the software should serve the JSON for that record, so there is a but in the code that is preventing this.

**Comment by nickdos** [comment]
I've tested this with just SOLR and it can't handle the braces chars, even when they are escaped according to the Lucene docs. The SOLR requests just hang. E.g.

http://localhost:8060/solr/bie/select?wt=json&q=guid:ALA_Caesia_sp._Koolanooka_Hills_\(R._Meissner_%26_Y._Caruso_78\)

So the longer term fix is to avoid both `&` and `(`,`)` characters (any of the SOLR escaped chars is probably a good idea - `+ - && || ! ( ) { } [ ] ^ " ~ * ? : \`), when generating the GUID from a string. There is already code that substitutes space for underscore, so it could be added there.

**Comment by charvolant** [comment]
The other option is simply to min a UUID for the name. This will mean that the IDs for these species (there's about 6,000 of them) will move about each ime we create a new index, however.

**Comment by nickdos** [comment]
Mmmm tempting solution as I don't like the fact that the same field has UUIDs and free text style IDs but then the IDs changing is not ideal. 

The code to remove Lucene escaped chars is a bit ugly, so would prefer to not use it:

`item.name?.replaceAll(/[\!\*\+\-\=\<\>\&\|\(\)\[\]\{\}\^\~\?\:\\\\/ "]+/,'_')`

If we could persist the UUIDs between indexing events, it would be nice. Could we hook into the code that holds previous identifiers (not provided by AFD, et al.) maybe?

**Comment by charvolant** [comment]
How about just replaceAll("[^A-Za-z0-9]", "_").replaceAll("__*", "_")

My grand unified taxonomy resolver does look after identifiers from different sources and historical trails. However, I don't have something that will take an old identifier and name and map it onto the current version. Can be added, though and it would be useful.

**Comment by nickdos** [comment]
Not quite right - but this works:

`.replaceAll("[^A-Za-z0-9]", "_").replaceAll("__*", "_")`

**Comment by nickdos** [comment]
Improved to simply `replaceAll("[^A-Za-z0-9]+", "_")`

```
groovy:000> out1 = test1.replaceAll("[^A-Za-z0-9]+", "_")
===> _the_S_entence_you_want_to_e_sca_pe
```
