### ISSUE TITLE
Autocomplete not recognising "Fungi"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#146]
E.g. http://bie.ala.org.au/ws/auto?q=fungi

Fungi is not listed in top 10 results.

**Comment by nickdos** [comment]
Similar issue with "PLANTAE", which is not appearing as the top hit:

![untitled](https://user-images.githubusercontent.com/532845/27210763-1968d818-5298-11e7-8554-67e595c89e8f.png)

**Comment by TaniaGLaity** [comment]
seems to be resolved - closing issue
