### ISSUE TITLE
Wrong GUID for AusFungi taxon

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#151]
http://bie.ala.org.au/search?q=Pycnoporus

first hit shows:

`guid: "897f67c3-cea1-4355-9bf5-0899ab51e00c"`

However, requesting that GUID returns a 404. 

@charvolant says the GUID should be `urn:lsid:indexfungorum.org:names:18433`.

**Comment by charvolant** [comment]
Recently built indexes have the correct guid. Rebuilding bie index to see whether the correct guid is picked up.

**Comment by charvolant** [comment]
Index has correct guid but bie-index still returning `897f67c3-cea1-4355-9bf5-0899ab51e00c` as the taxon guid

**Comment by charvolant** [comment]
Fixed classification map bug. Fix rolled into JDK8/bootstrap3 work.

**Comment by adam-collins** [comment]
Appears working.
