### ISSUE TITLE
Taxon page from search results gives 404

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#157]
https://bie.ala.org.au/search?q=Aureobasidium

First hit is a 404: https://bie.ala.org.au/species/9b0d88ff-a677-4c62-a9bd-83744a0c2e56

**Comment by jhpoelen** [comment]
I just noticed some integration tests have started failing on species guid lookups like:

http://bie.ala.org.au/ws/species/urn:lsid:biodiversity.org.au:afd.taxon:e6aff6af-ff36-4ad5-95f2-2dfdcca8caff.json

whereas an associated lookup by name http://bie.ala.org.au:80/ws/search.json?q=Macropus%20rufus succeeds. 

@nickdos is this the same issue?

**Comment by nickdos** [comment]
Yes, there is a problem with server, thanks for letting us know.

**Comment by jhpoelen** [comment]
@nickdos GloBI's ALA integration tests are passing again, thx!

**Comment by adam-collins** [comment]
Appears fixed.
