### ISSUE TITLE
Check AFD genus (2017 Sept release)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#158]
https://bie.ala.org.au/search?q=Bastilla

currently shows that _Bastilla_ is a synonym of _Dysgonia_. AFD lists _Bastilla_ as an accepted name and lists a number of species under it, that the ALA currently shows as being under _Dysgonia_.

https://biodiversity.org.au/afd/taxa/Bastilla
https://biodiversity.org.au/afd/taxa/Dysgonia;Ophiusini

So with the new Septemer release, please check if this taxon has been updated to match AFD.

**Comment by charvolant** [comment]
Correctly shown in new data
