### ISSUE TITLE
Importing and searching for quoted names

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#16]
Some names have a form such as "\"Cyclophora\" turneri" -- see http://biodiversity.org.au/afd.name/564610.html These appear in the bie as "\Cyclophora\ turneri" 

It doesn't seem to be possible to find them with a query such as /bie-index/search?q=Cyclophora+turneri although /bie-index/taxon/urn:lsid:biodiversity.org.au:afd.name:564610 returns the description and /bie-index/search?q=\Cyclophora\+turneri finds the taxon

**Comment by charvolant** [comment]
Caused by DWCA not supporting escaped quotes in DWCA files. Instead, they adhere to the double quoted version, so the name should be supplied as """Cyclophora"" turneri"

**Comment by adam-collins** [comment]
Appears working.
