### ISSUE TITLE
search for genus [Abbreviata] now no longer returns family [Physalopteridae]

### ISSUE THREAD

**Issue by jhpoelen** [AtlasOfLivingAustralia/bie-index#165]
As part of automated integration test of [GloBI](https://globalbioticinteractions.org) at https://travis-ci.org/jhpoelen/eol-globi-data/builds/296007236#L1183 , I noticed that a previously found (and expected) taxon hierarchy for genus Abbreviata no longer holds.

The first time the change was detected was on 30 Oct 2017 and the observed last time the assertion held was 23 Oct 2017. 

Expected:

kingdom | phylum | class | subclass | order | suborder | superfamily | family | subfamily | genus
--- | --- | --- | --- | --- | --- | --- | --- | --- | ---
Animalia | Nematoda | Chromadorea | Plectia | Spirurida | Spirurina | Camallanoidea | Physalopteridae | Physalopterinae | Abbreviata

Actual: 

kingdom | phylum | class | subclass | order | suborder | subfamily | genus
--- | --- | --- | --- | --- | --- | --- | ---
Animalia | Nematoda | Chromadorea | Plectia | Spirurida | Spirurina | Physalopterinae | Abbreviata

Could you please help me understand whether this is a bug or expected behavior?

**Comment by CamSlatyer** [comment]
rectified in Dev

**Comment by adam-collins** [comment]
appears working https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/39683706-f5b1-43be-934b-5fdf4f5e3150#classification
