### ISSUE TITLE
Invalid names with an acceptedNameUsageID

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#17]
AusMoss contains invalid names with a link to the accepted name for the invalid name. 

In general, we'll treat these as synonyms. However, there needs to be some way of flagging that an invalid name has been used and (out of the goodness of our hearts) we've converted it into an accepted name. So the taxonomicStatus will still be "invalid" rather than "synonym".

**Comment by adam-collins** [comment]
I do not know how to test for this.
