### ISSUE TITLE
Names literature and linking to the scientists who publish taxonomy

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#174]
Idea from a user:

> Greetings,
> 
> the people who named these plants and animals were people, with their own 
> story. Any chance of adding their details to the ALA in future?
> 
> Lyndon Z

If we can get decent linking through to the publication metadata for each name, then we should also be able to link to WikiPedia articles, etc., about the authors of these publications.

**Comment by charvolant** [comment]
GBIF provides a list of common abbreviations for author comparison which could be used to handle things like "Benth."

**Comment by adam-collins** [comment]
The names and literature tabs have since been updated, as well as the inclusion of wikipedia and lists information. That's enough for now.
