### ISSUE TITLE
Add an API call to allow name-index matching

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#175]
Allow access to the functionality of the ala-name-matching lookup, where names can be matched and disambiguated via higher taxonomy information. The query would be of the form

```
{
  "kingdom": "Animalia",
  "family": "Macropodidae",
  "scientificName": "Osphranter rufus",
  "vernacularName": "Red kangaroo"
}
```

with a result of the form

```
{
  "kingdom": "Animalia",
  "kingdomID": "urn:lsid:biodiversity.org.au:afd.taxon:4647863b-760d-4b59-aaa1-502c8cdf8d3c",
  "phylum": "Chordata",
  "phylumID": "urn:lsid:biodiversity.org.au:afd.taxon:065f1da4-53cd-40b8-a396-80fa5c74dedd",
 ...
  "guid": "urn:lsid:biodiversity.org.au:afd.taxon:190ad4b1-0444-4791-96a5-ee514438d7e6"
 "nameType": "SCIENTIFIC",
 "issues": [ ]
}
```

Allow a GET request with fields given as parameters. Allow a POST request with either a single request or a list of requests.

**Comment by adam-collins** [comment]
I think the https://github.com/AtlasOfLivingAustralia/ala-namematching-service fills this requirement.
