### ISSUE TITLE
Common name field contains scientific names

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#177]
Reported by user, e.g. https://bie.ala.org.au/search?q=Hygrocybe show results 

> species: Hygrocybe austropratensis A.M.Young – **Hygrocybe Austropratensis**

The last string in bold should be a common name but in these cases the scientific name is appearing twice and is incorrectly formatted (capitalised specific epithet == bad).

Offending data source is [New South Wales: Classification codes under the Threatened Species Conservation Act 1995](https://collections.ala.org.au/public/show/dr650), which is marked as a common name source but providing scientific names.

**Comment by charvolant** [comment]
There are quite a few cases where vernacular name = scientific name (modulo case) in the list.

This seems to be a specific problem with the data in the list itself. We can fix the source data. However, this is an 'official' list and, probably, shouldn't be directly monkeyed with. I'll add a step in the processing that discards vernacular names that are the same as the scientific name for list sources.

We can reload the BIE but leave the name matching index alone.

**Comment by TaniaGLaity** [comment]
appears to have been resolved using the above example
