### ISSUE TITLE
NZOR/AFD duplication

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#178]
> Hi Lee,
>
> I just came across a problem in ALA.  This species (https://bie.ala.org.au/species/NZOR-4-129071#tab_recordsView) is a synonym of this species (https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:09b38f9f-eae8-4a73-93b6-2bb0d2f7f1ba).  So says the ABRS Australian Faunal Directory: https://biodiversity.org.au/afd/taxa/Stercorarius_antarcticus_lonnbergi. It might be a good idea to merge them.  This species (https://bie.ala.org.au/species/NZOR-4-120330) also appears to be a synonym.  It might just be worth taking a second look at the taxonomic designations of all the skuas and jaegers.  It looks like they’re all in a state of confusion.
>
> Cheers,
Mike Lohr

**Comment by CamSlatyer** [comment]
Dev version deals with this one.

**Comment by adam-collins** [comment]
Appears done https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/b3f6dbaa-10ad-499c-ac25-a906afce89a0#names
