### ISSUE TITLE
Update image web service not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#179]
The [index page](http://bie.ala.org.au/ws/) describing the web services lists:

> Update Image | POST IMG | /ws/import/updateImages { "guidImageList": [ {"guid": GUID, "image": "63c06642-ab33-48b9-b04b-2f321d24f104"} ] }

However when I try to POST to this end point I get an error:

```
{
    "timestamp": 1516849402147,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/ws/import/updateImages"
}
```

**Comment by nickdos** [comment]
I also tried `/ws/updateImages` (by looking at UrlMappings file) I get an error HTML page that says "An error occurred".

**Comment by adam-collins** [comment]
This is not in the openapi listing. A working alternative exist https://bie-ws.ala.org.au/ws/openapi#/admin%20webservices/setImages
