### ISSUE TITLE
Preferred common name

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#18]
Marine species in CAAB have a standard, preferred common name. This is important, since it's an official commercial name used to ensure that people are actually buying the same species without mislabelling. 

There needs to be a way of prioritising or flagging common names so that they can be displayed before other common names and flagged as "official" in some way.

taxonomicStatus and nomenclaturalStatus are DwC terms but apply to the scientificName/taxon, so I suggest what we don't used that term. I'd suggest adding an additional column to vernacularNames.csv with a vernacularNameStatus term drawn from a vocabulary. In order of priority:
- legislated - The name appears in legislation as a name for the species. This might include "scientific" names that are no longer considered valid but which are lying about in legislation???
- standard - The name appears in a standards document as a standardised common name
- preferred - A preferred common name for some reason
- common - A widely used common name
- local - A locally used common name

All of these are fairly region specific. So, in theory, other terms should be added: locationID and locality, in a similar way to the distribution.txt in a taxon dwca, to give a feel for the regional scope of these names.

For an example, _Hoplostethus atlanticus_ might have an entry of

taxonID,nameID,datasetID,vernacularName,vernacularNameStatus,locationID,locality,language
37255009,,drYYY,Orange Rougy,standard,AU,Australia,en-AU
37255009,,drYYY,Deep-sea Perch,common,,en-AU

**Comment by djtfmartin** [comment]
A vernacularNameStatus makes sense to me although we'd need to know how these values are prioritised. I assume it would be in the order specified above.

Theres quite a few services in BIE that will just want to serve the single "best" common name for a taxon.

**Comment by charvolant** [comment]
Yeah. I would think that legislation trumps documents trumps widely used trumps widely recognised trumps twanging banjos. Those were the categories I could think of. However, it's probably best to have a general, totally (or partially?) ordered vocabulary somewhere.

**Comment by charvolant** [comment]
Functionality added long ago.
