### ISSUE TITLE
Add field list parameter to species and search queries

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#180]
Allow something like

https://bie.ala.org.au/ws/search.json?q=Mirawara&fq=rank:genus&fq=rk_kingdom:ANIMALIA&fl=kingdom

The fields of the web service don't quite match the fields of the underlying solr index, so use the web service fields.

**Comment by charvolant** [comment]
Actually, a field filter on the species query doesn't make a great deal of sense. So just searches.

**Comment by adam-collins** [comment]
Appears working
