### ISSUE TITLE
Include non-Linnaean ranks in download columns

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#183]
As well as the standard kingdom, phylum, class, etc. columns, include information on super- sub- and infra- ranks, as well as tribe, division, etc. when populating the download columns.

**Comment by charvolant** [comment]
Also include parent taxonID, rank etc. so that someone can make their own tree.

**Comment by charvolant** [comment]
Also include header information so that people can navigate the meaning of the various ranks.

**Comment by adam-collins** [comment]
Still required for `/download`, e.g. https://bie-ws.ala.org.au/ws/download?q=https://biodiversity.org.au/afd/taxa/d03c4b24-5222-4781-a8ee-0aa8f905f4f7
