### ISSUE TITLE
missing (legacy) AFD uris

### ISSUE THREAD

**Issue by jhpoelen** [AtlasOfLivingAustralia/bie-index#187]
I noticed that the following uris /name for afd species no longer resolve:

```
urn:lsid:biodiversity.org.au:afd.taxon:06c3c692-760c-411a-bb66-d580c2b3d0d4	Lecithochirium magnus
urn:lsid:biodiversity.org.au:afd.taxon:7d65609e-5a44-4c64-b2fa-70d4b3bf9b9e	Heligmonoides mackerrasae
urn:lsid:biodiversity.org.au:afd.taxon:e16d8dca-38d1-43fa-b5c5-6060b88cbb0b	Heligmonoides emanuela
```
Please confirm that this is expected behavior. If so, please let me know why the names no longer resolve or get redirected.

Emerged in a review of GloBI's taxon graph at http://doi.org/10.5281/zenodo.1213465 . Also see 
 https://github.com/globalbioticinteractions/nomer/issues/5#issuecomment-388415967 .

**Comment by adam-collins** [comment]
This is expected behaviour.
