### ISSUE TITLE
Code common names

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#19]
People sometimes use CAAB codes as a shorthand for a species name. It would be useful to include these in some way as a form of vernacular name.

I'm not sure what adding something like "37311074" as a common name would do to the index.

**Comment by djtfmartin** [comment]
I think a separate index "identifier" field which can support multiple values might make more sense. This could accomodate these alternative identifiers push the old identifiers from AFD.

**Comment by charvolant** [comment]
To go into the taxon.csv file, I would guess, with vertical bar (|) as separator?

The other option is to add another extension, identifiers.csv, similar to vernacularNames.csv. That would seem to me to be preferable, since it means that we can add things like source metadata, etc.

**Comment by djtfmartin** [comment]
+1 for the extension.

**Comment by charvolant** [comment]
I'll give a try on the CAAB stuff and see what it looks like.

**Comment by charvolant** [comment]
Identifiers can be put into the following extension:

```
<extension encoding="UTF-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.gbif.org/terms/1.0/Identifier">
    <files>
      <location>identifiers.csv</location>
    </files>
    <coreid index="0" />
    <field index="0" term="http://rs.tdwg.org/dwc/terms/taxonID"/>
    <field index="1" term="http://purl.org/dc/terms/identifier"/>
    <field index="2" term="http://purl.org/dc/terms/title"/>
    <field index="3" term="http://purl.org/dc/terms/subject"/>
    <field index="4" term="http://purl.org/dc/terms/format"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/datasetID"/>
    <field index="6" term="http://purl.org/dc/terms/source"/>
    <field index="7" term="http://ala.org.au/terms/status"/>
  </extension>
```

| term | description |
-----------------------
| taxonID | The taxonID appearing in the core file |
| identifier | The alternate identifier |
| title | An optional descriptive title for the identifier |
| subject | Optional semi-colon separated keywords for the identifier |
| format | The format of the identifier |
| datasetID | The name dataset |
| source | The source of the  identifier |
| status | A keyword describing what the identifier is from a controlled vocabulary (see below) |

A suggested vocabulary for the status keyword is:

* *current* An alternative identifier that is currently used
* *replaced* An identifier that has been replaced by the current taxonID
* *unknown* An identifier with unknown status

**Comment by djtfmartin** [comment]
looks good to me

**Comment by charvolant** [comment]
I've constructed versions for CAAB (CAAB codes) and AFD (Previous taxon IDs) and imported them into bie-dev

**Comment by adam-collins** [comment]
I guess this is done.
