### ISSUE TITLE
bulkGuidLookup should do lookup on old GUID

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/bie-index#193]
bulkGuidLookup should new GUID info for old GUID.
for eg: urn:lsid:biodiversity.org.au:afd.taxon:e7437fab-11f6-4dc1-b8c5-bbe4d616c96a

https://bie.ala.org.au/ws/species/urn:lsid:biodiversity.org.au:afd.taxon:e7437fab-11f6-4dc1-b8c5-bbe4d616c96a is being redirected to https://bie.ala.org.au/ws/species/urn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A6b3fd0b6-8e39-4692-93ee-372391ff37b0

**Comment by adam-collins** [comment]
As a general rule GUIDs are replaced when there is an updated, losing the old GUID.
