### ISSUE TITLE
Searches with voucher names return confused results

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#199]
Possibly a result of the parentheses being interpreted by the solr query? For example,

https://bie.ala.org.au/search?q=Dillwynia+sp.+trichopoda returns sensible results.

https://bie.ala.org.au/search?q=Dillwynia+sp.+trichopoda+%28Maiden+%26+Boorman+s.n.+40290%29 does not

https://bie.ala.org.au/search?q=Dillwynia+sp.+trichopoda+Maiden+Boorman+s.n.+40290 is sort of OK.

The voucher name appears in the scientific name for search purposes, since the authorship is given as NSW Herbarium

**Comment by charvolant** [comment]
It must be possible to do this without escaping since a straight solr query in q= is not only possible but sometimes required. Moved to the bie-plugin.

**Comment by charvolant** [comment]
This will also require fixing the BIE so that it talks nicely to the SOLR cloud when it does an import. Otherwise, the image and occurrence count scans will cause explody bits.

**Comment by charvolant** [comment]
Awaiting review of https://github.com/AtlasOfLivingAustralia/bie-index/pull/210

**Comment by M-Nicholls** [comment]
reviewed

**Comment by javier-molina** [comment]
It is related to FD ticket https://support.ehelp.edu.au/a/tickets/20005
