### ISSUE TITLE
Resolve old LSIDs

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#20]
LSIDs for taxa, particularly those for AFD, tend to move about under fire. Since we're using the LSID as the key, it's possible for someone looking up a species under an old LSID to suddenly find a missing page. This can be a problem for generated species lists.

With the AFD, it's possible to build a history of previous LSIDs. It should be possible to supply an additional extension in the DwCA that gives a list of known "previous" LSIDs.

**Comment by charvolant** [comment]
The identifiers extension can be used to list past identifiers. See https://github.com/AtlasOfLivingAustralia/bie-index/issues/19 with the following format:

"urn:lsid:biodiversity.org.au:afd.taxon:21024684-6cbd-4d1a-90f2-879c052ee85f","urn:lsid:biodiversity.org.au:afd.taxon:8d46aea4-0339-4065-938d-18c3bd28dfb9","Previous AFD LSID","","lsid","drXXX","AFD","replaced"

**Comment by nickdos** [comment]
Just adding a note to this to test the webservices which take a GUID input, that they can handle old LSIDs and resolve to the current one before processing output.

from Ely:
> I think I remember that after the LSID issue occurred last time, some new code was put in so that old LSIDs would be permanently resolvable. However, being cautious, we’d rather not be trying to export a bunch of records at the same time you’re pushing in the new updates just in case everything breaks again.

**Comment by nickdos** [comment]
Making a list of endpoints that should support this feature (taken from current [BIE WS page](http://bie.ala.org.au/ws/)):
- [ ] `/species/${guid}`
- [ ] `/species/shortProfile/${guid}.json`
- [ ] `/species/info/${guid}.json`
- [ ] `/species/moreInfo/${guid}.json`
- [ ] `/ws/species/bulklookup.json`
- [ ] `/ws/species/guids/bulklookup.json`

**Comment by PeggyNewman** [comment]
The Museum Victoria field guides' CMS use these web services. Their starting point is often the LSID recorded in their collection repository EMu. 

http://bie.ala.org.au/ws/species/LSID.json
http://biocache.ala.org.au/ws/occurrences/facets/download?q=lsid:LSID

**Comment by adam-collins** [comment]
I do not think we keep track of all historical LSIDs, or will.
