### ISSUE TITLE
Assorted name data related issues

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#201]
Issues arising from Betty Woods' investigations of the current name indexes. This issue is for bie-related problems. The equivalent issue for name matching and source merging is https://github.com/AtlasOfLivingAustralia/ala-name-matching/issues/58

**Comment by charvolant** [comment]
ALA still having problems with synonyms of funny accepted names
Hi
Here are a couple of examples.
Eg Polyscias sambucifolia subsp. 1 is actually a synonym of Polyscias sambucifolia subsp. Long leaflets ..........
It is not a synonym of Polyscias sambucifolia subsp. as cited in ALA.


A search directly on Polyscias sambucifolia subsp. Long leaflets brings up the full name in the drop down menu and has a meaningful result.

**Comment by charvolant** [comment]
Petunia x atkinsiana
Hi Anna
Another instance of Flora of New Zealand going their own way with spelling of accepted names, and ALA allowing the New Zealand spelling to override the CHAH majority spelling.

**Comment by javier-molina** [comment]
Relates to https://support.ehelp.edu.au/a/tickets/20088

**Comment by javier-molina** [comment]
Relates to FD ticket https://support.ehelp.edu.au/a/tickets/20598

**Comment by CamSlatyer** [comment]
Name prioritisation in NZOR versus APNI - strategic taxonomy conversation

**Comment by adam-collins** [comment]
Appears fixed as per the comments on the linked issue. e.g.
- Polyscias sambucifolia subsp. 1 is a synonym of Polyscias sambucifolia subsp. Long leaflets, https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2897497#names
- https://bie.ala.org.au/species/Petunia%20x%20atkinsiana is returning an APC result.
- (from linked issue) https://bie.ala.org.au/species/Paracaleana%20minor is returning an APC result.
- (from linked issue) https://bie.ala.org.au/species/Chiloglottis%20trapeziformis is returning an APC result.
