### ISSUE TITLE
NZOR/AusFungi issues

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#206]
Reported by a user: https://support.ehelp.edu.au/a/tickets/23649

Example name: https://bie.ala.org.au/search?q=Botryobasidium

AVH is only matching on the NZOR, so record count is far too low: 

https://avh.ala.org.au/occurrences/search?taxa=Botryobasidium
vs
https://avh.ala.org.au/occurrences/search?q=qid:1538022359480

Please update ticket when closed.

**Comment by TaniaGLaity** [comment]
appears to be fixed
