### ISSUE TITLE
Optionally download synonyms as well as accepted taxa

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#207]
It should be possible to do an "include synonyms" in a download, so that e.g a query for kingdom:Fungi includes taxa linked to an accepted concept in Fungi

**Comment by adam-collins** [comment]
Related to https://github.com/AtlasOfLivingAustralia/bie-index/issues/183

I wonder if this should be optional because it could add many rows to the output if records matching the criteria `acceptedConceptID=taxonID` are also included.

**Comment by adam-collins** [comment]
The only way I can see this working is to add another column during indexing, `additionalIdentifierNames`. This will be the same as `additionalIdentifiers` except that it will contain the additional names not the additional IDs.
