### ISSUE TITLE
API call to query taxonomy metadata and incremental update

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#212]
Allow an external user to query the taxonomy and get information about the version and currency so that they can see whether their version matches the ALA version.

Ideally, allow a list fo changes to be listed so that an incremental update can be made.

**Comment by adam-collins** [comment]
Because adhoc names DWCAs can be added to the index this enhancement (incremental names index updates) does not exist. 

Raise this again should it exist.
