### ISSUE TITLE
Add APII as a source of authoritative images

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#216]
https://collections.ala.org.au/public/show/dr413

**Comment by adam-collins** [comment]
This requires adding a `preferred` `fq` to `*-image-lists.json` in ala-install, only for ALA. The `fq` is `dataResourceUid:dr413`

**Comment by adam-collins** [comment]
ala-install pull request https://github.com/AtlasOfLivingAustralia/ala-install/pull/757

**Comment by TaniaGLaity** [comment]
@adam-collins and @joe-lipson how do we add more authoritative images sources?

**Comment by adam-collins** [comment]
@TaniaGLaity We add the list or occurrence `dr*` to the config. Please create an issue with details after it is prepared.
