### ISSUE TITLE
childconcepts output for Plantae missing direct decendants

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#217]
Related to AtlasOfLivingAustralia/bie-plugin/issues/121

When calling https://bie.ala.org.au/ws/childConcepts/http://id.biodiversity.org.au/node/apni/9443092

there are no major rank children at 2000 or 3000 `rankID` which you would expect for a kingdom (`rankID` 1000) taxon. Closest relative (major rank) is 2x 4000 `rankID` taxa  and closest minor rank relative is 1200 (subkingdom).

Fix is to work out why none of the 2000 and 3000 `rankID` taxa are being shown.

**Comment by adam-collins** [comment]
Appears working https://bie.ala.org.au/ws/childConcepts/https://biodiversity.org.au/afd/taxa/4647863b-760d-4b59-aaa1-502c8cdf8d3c#classification
