### ISSUE TITLE
HETEROPTERA label

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/bie-index#222]
from support ticket: https://support.ehelp.edu.au/a/tickets/25911  

On the Atlas of Living Australia website for HETEROPTERA it says Gerrids, which is just one of the many families. I think it should say True Bugs here.

https://bie.ala.org.au/species/urn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ab809bc05-d1c2-4664-8727-cc6493b7a3cd#classification

**Comment by nickdos** [comment]
This is an issue with AFD - if you look at their page for this taxon, they do refer to "true bugs" in the text but not as a common name (the provide Gerrids, etc). https://biodiversity.org.au/afd/taxa/b809bc05-d1c2-4664-8727-cc6493b7a3cd.

**Comment by TaniaGLaity** [comment]
as we are using AFD for the authoritative source for common name - and this matches for this taxa, closing this issue
