### ISSUE TITLE
Genus Nihoa should refer to spiders not birds

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/bie-index#226]
From https://support.ehelp.edu.au/a/tickets/27235

> Hi,
When checking the Barychelidae spider family I note that the genus Nihoa is listed but all the descriptive material including references in the 'Overview' refer to a bird species (Telespiza ultima).

The offending record in BIE is

Ely pointed out to the offending record.

https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:43696beb-8a3d-4cb2-ad05-74ef6501064e#classification

While Miles mentioned that the right record for Nihoa in EOL should be:

https://eol.org/pages/111480

Looks like BIE is picking the first record from this search:

https://eol.org/search_results?utf8=%E2%9C%93&q=nihoa

**Comment by javier-molina** [comment]
There is a CR related to this https://github.com/AtlasOfLivingAustralia/bie-plugin/pull/131

**Comment by charvolant** [comment]
The EoL search needs to be more specific. It currently filters on class but that captures too many insects. Changed to try filtering on family first, then order, class, phylum and kingdom.

**Comment by charvolant** [comment]
Fixed in https://github.com/AtlasOfLivingAustralia/bie-plugin/pull/136
