### ISSUE TITLE
No Worms category

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/bie-index#227]
This comes originally from 
 
https://support.ehelp.edu.au/a/tickets/27235

The point about no worms listed (also applies to many other lower taxa e.g. Protista, Bryozoa, Nematoda, Annelida etc. etc.). When trying to ‘Record a sighting’ under ‘Identification tags’ many groups are listed but nothing lower than Molluscs.

**Comment by adam-collins** [comment]
Duplicate of https://github.com/AtlasOfLivingAustralia/bie-index/issues/104
