### ISSUE TITLE
Autocomplete garbage results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#230]
https://bie-ws.ala.org.au/ws/search/auto.json?q=acacia+ligul

should return "Acacia ligulata" as the first result but its the 9th result and many of the results above bear no resemblance to the query at all.

E.g. 5th hit: `matchedNames: ["Acizzia uncatoides"]`.

AVH screenshot:

![image](https://user-images.githubusercontent.com/532845/52250653-f79c9c00-294c-11e9-8e07-0cefd094b43d.png)

**Comment by charvolant** [comment]
Note when using the solr suggester that the temporary index is built in the /tmp dir. To change this add -Djava.io.tmpdir=/data/tmp

**Comment by adam-collins** [comment]
Appears fixed
