### ISSUE TITLE
BIE - Index IEK names to allow searching on those terms

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/bie-index#236]
As an indigenous language user
I want to search using IEK terms
So that I can find species information by the names I know organism by

Assumption: Once the IEK lists of terms are added to the TALEND indexing job and the index is run, the terms will be able to be used for searching in the BIE and the biocache. This story is to ensure the list is indexed and to test the terms can be used for search. Any issues found may require bugs to be raised in either the BIE-general repository ot the biocache repository.

Requirements
- Ensure lists with IEK language terms are added to the TALEND indexing job
- Once the indexing job is run, a user should be able to enter an IEK term in the ALA search and return species page information for the associated taxon - BIE
- Once the indexing job is run, a user should be able to enter an IEK term in the ALA search and return occurrence records for the associated taxon - Biocache

**Comment by m-hope** [comment]
Assuming IEK names will be handled as some form of "Common" name, then this feature is already available (eg: search for Manuea in the BIE... which is one of the Moari names for Kunzea ericoides).  This also works for the Quick Search bar in the Biocache occurrence records.

What we need to ensure is that, if we separate the IEK from the other common names from a display point of view, then these searches will still work.

**Comment by TaniaGLaity** [comment]
appears to be fixed - closing ticket
