### ISSUE TITLE
BIE - Allow language dictionaries to be externally configurable

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/bie-index#237]
As an indigenous knowledge holder
I want to control when IEK terms in my language are made public
So that I can share development data with the ALA before it is ready to be made publicly accessible

Background:
Currently, language terms are stored directly in the indexing code. This means that when this code is published terms become publicly accessible, whether or not the environment being used is a restricted dev environment or or a publicly accessible environment.

IEK names lists will be created in the lists tool, don't know if they can be accessed directly from there or if they will need to be manually or automatically copied elsewhere and stored for access.

Requirements:
- Provide the ability to remove the name terms from being embedded in the code, and allow them to be looked up by the system.

**Comment by RobinaSanderson** [comment]
Hi @charvolant -  do we need to specify the format for the list of terms and is it sufficient to store them only in the lists tool?

**Comment by m-hope** [comment]
If we are using the lists tool to store IEK names to be loaded into the ALA name index, then giving the owner the ability to edit a list is already available.  However, as far as I am aware, the lists tool is entirely public and no data stored in it can be embargoed.  

Additionally, given the hassles we've had obtaining permissions to use IEK data, I'm not sure we'd want to store anything in the ALA that first doesn't have permissions even for developmental purposes.

**Comment by RobinaSanderson** [comment]
Only data that is authorised for public access in the ALA species pages should be added to the lists tool and made available this way. Lists of IEK names not authorised can be made private so they are not publicly accessible. As such this issue will be closed.
