### ISSUE TITLE
Species page links with trailing dot throw error

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#238]
Reported by vjrj on Slack:

> For instance: https://especies.gbif.es/search?q=ginkgo (see first result) generate links like: [https://especies.gbif.es/species/Ginkgo%20L.](https://especies.gbif.es/species/Ginkgo%20L.)

which shows error:

```
Error 500: Internal Server Error
URI
/species/Ginkgo%20L.
Class
java.lang.StringIndexOutOfBoundsException
Message
String index out of range: 1
-----
 Line | Method
->> 1963 | substring                     in java.lang.String
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    256 | getPropertyNameRepresentation in grails.util.GrailsNameUtils
|    215 | getPropertyName . . . . . . . in     ''
|     33 | toUrlElement                  in grails.web.CamelCaseUrlConverter
|    201 | getActionName . . . . . . . . in org.grails.web.mapping.DefaultUrlMappingInfo
|     98 | populateParamsForMapping      in org.grails.web.mapping.AbstractUrlMappingInfo
```

Which suggests this is a Grails issue, related to looking for a file extension (maybe).

**Comment by nickdos** [comment]
Issue moved to [AtlasOfLivingAustralia/bie-plugin #147](https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/147) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vjrj** [comment]
Seems to me a ala-bie issue:
Compare:
* [https://especies.gbif.es/species/Ginkgo%20biloba%20L.](https://especies.gbif.es/species/Ginkgo%20biloba%20L.)
with the ws: 
* [https://especies-ws.gbif.es/species/Ginkgo%20biloba%20L.](https://especies-ws.gbif.es/species/Ginkgo%20biloba%20L.)
