### ISSUE TITLE
Improve relevance ranking of searches

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#24]
E.g. search for "acacia" - Acacia genus should be first hit but it is currently the 6th hit. 

http://bie-dev.ala.org.au/ala-bie/search?q=acacia

I think this could be improved by giving the "name string" match a higher boost vs other text fields ???

**Comment by nickdos** [comment]
https://wiki.apache.org/solr/SolrRelevancyFAQ

is a good starting place.

**Comment by adam-collins** [comment]
Appears done.
