### ISSUE TITLE
Bulklookup failure in ALA4R

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/bie-index#246]
Searching guids is returning a failure in ALA4R. Output file attached. Many 404s. It looks like it's happening when sending through dummy values and ALA4R expects it not to fail.

POST /ws/species/guids/bulklookup
[testthatoutput.txt](https://github.com/AtlasOfLivingAustralia/bie-index/files/3057326/testthatoutput.txt)

**Comment by charvolant** [comment]
So we're returning a 404 because the requested GUID isn't there and that's what we usually return for that kind of thing. Is there a more appropriate response?

**Comment by ansell** [comment]
`ala-bie` seems to be handling requests for unknown taxa fairly cleanly, passing on the 404 to the user:

```
==> /var/log/tomcat8/catalina.out <==
Failed calling web service. class java.io.FileNotFoundException https://bie-ws.ala.org.au/ws/taxon/HYGROCYBE+ASTATOGALA URL= https://bie-ws.ala.org.au/ws/taxon/HYGROCYBE+ASTATOGALA.

==> /var/log/nginx/access.log <==
[REDACTED] - - [03/May/2019:11:57:07 +1000] "GET /species/HYGROCYBE+ASTATOGALA HTTP/1.1" 404 5598 "http://www.google.com/" "Mozilla/5.0 (Linux; Android 9; Pixel) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36" "[REDACTED]" request_time=0.046 upstream_response_time=0.044 upstream_connect_time=0.000 upstream_header_time=0.044 upstream_cache_status=MISS
```

@peggynewman Can you fix this on the ALA4R side so that it handles HTTP 404/400 codes as user errors rather than server errors?

**Comment by charvolant** [comment]
The alternative view is that 404 means couldn't find the endpoint and it should return '[]' for not found.

**Comment by peggynewman** [comment]
@charvolant that's what has been happening before. Sorry I haven't responded. I notice some other issues are related to this one, eg
https://github.com/AtlasOfLivingAustralia/biocache-service/issues/375#issuecomment-491646961
What's the best course of action for ALA4R?

**Comment by ansell** [comment]
I am not familiar with R, but there are some references to another bie service returning 404 which may be useful for copy-pasting or reusing the pattern for this case https://github.com/AtlasOfLivingAustralia/ALA4R/blob/master/R/species_info.R#L52-L54

**Comment by adam-collins** [comment]
Because the name is a path variable I think leaving it as a 404 is correct.

There is a potential issue when doing large searches with the bulk service. Refer to issue https://github.com/AtlasOfLivingAustralia/bie-index/issues/244
