### ISSUE TITLE
Common name results should include accepted taxon name

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#247]
Currently, common names [search results show](https://bie-ws-test.ala.org.au/ws/search?q=duck+platypus&fq=idxtype:%22COMMON%22):

![image](https://user-images.githubusercontent.com/532845/55925343-a95b9000-5c50-11e9-9530-f68837a22dcb.png)

It would be very useful to also include the **accepted taxon name** in the results (associated with the `taxonGuid`) so we can include this on the species search results.

**Comment by TaniaGLaity** [comment]
appears to be fixed - closing issue
