### ISSUE TITLE
AFD common names question

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#254]
See support ticket https://support.ehelp.edu.au/a/tickets/32936

Question from user about the lack of results for the search [`Gippsland Water Dragon`](https://bie.ala.org.au/search?q=Gippsland+Water+Dragon) and 'Eastern Water Dragon`. The latter resolves to `Intellagama lesueurii` but should also be associated with the subspecies ` Intellagama lesueurii lesueurii` (according to other sources).

[`Intellagama lesueurii howitti` ](https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:d32717c5-cb3d-4326-ad76-0c002cdb1594) does not have a common name associated but I'm 90% sure it used to have the common name `Gippsland Water Dragon`.

Is this a issue with the AFD data or are we losing it somewhere in processing?

**Comment by charvolant** [comment]
AFD currently doesn't have Gippsland Water Dragon listed. I've passed this on to AFD to decide what to do.
