### ISSUE TITLE
Remove link identifiers

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#255]
They cause all kings of trouble whenever the index changes and a link identifier goes away.

**Comment by Rita-C** [comment]
Link identifier with special characters caused error in bie, refer to https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/199

**Comment by Rita-C** [comment]
Hi @charvolant , has this been resolved by fix of bie-plugin#199?

**Comment by charvolant** [comment]
@Rita-C The special characters issue has been fixed. Either by refusing to mint a link identifier or stripping it of unacceptable characters in the bie-index. It's a sort of moot point whether link identifiers are a good thing or not but, right now, they're not causing any trouble, so I'll close this issue and remove it from the backlog.

**Comment by Rita-C** [comment]
thanks @charvolant
