### ISSUE TITLE
Add ability to index regions (ALA)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#26]
Current BIE has this, so we should continue to support it.

E.g. http://bie.ala.org.au/search?q=new&fq=idxtype:REGION

**Comment by djtfmartin** [comment]
Ive already had a stab at this, but its not in production for ALS

https://github.com/AtlasOfLivingAustralia/bie-index/blob/master/grails-app/controllers/au/org/ala/bie/ImportController.groovy#L96

**Comment by djtfmartin** [comment]
Done and in production for ALS.

http://species.als.scot/search?q=loch
