### ISSUE TITLE
Create a set of functional tests for webservices

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#27]
We need to ensure this new version is backwards compatible with current production version (bie-service), so we need a set of functional tests that are developed against the old version and then tested on the new version. 

In order to determine what end points to test, the access logs should be mined for unique URLs and then used to determine both end points and params to test with.

This article by Angel may be helpful: http://aruizca.com/integrated-vs-functional-testing-how-to-test-rest-apis-in-grails-using-spock/

**Comment by nickdos** [comment]
Would be nice if test code could read test cases from an external JSON or Groovy file, so that new tests could be added without compiling code.

**Comment by sbearcsiro** [comment]
@charvolant I have put together the basic workings of a test harness here sbearcsiro/functional-test-harness.  I'm looking for feedback as to whether it would meet your needs bie WS testing
