### ISSUE TITLE
swagger configuration

### ISSUE THREAD

**Issue by shahmanash** [AtlasOfLivingAustralia/bie-index#273]
The swagger in bie-index in ALA is probably mis-configured, it misses out `/ws` . 
The deployment context path in the URL that it presents, so trying out the API results in 404
for eg : `https://bie.ala.org.au/search/auto?q=cat` is the Request URL that the swagger  generates, but it should have been ` https://bie.ala.org.au/ws/search/auto?q=cat`

**Comment by charvolant** [comment]
Add common paths via https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by adam-collins** [comment]
This has been updated since this issue. https://bie-ws.ala.org.au/ws/openapi
