### ISSUE TITLE
idxType filter on autocomplete is broken

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#277]
For example https://bie-ws.ala.org.au/ws/search/auto.json?q=platypus&idxType=COMMON should return a link to Ornithorhynchus anatinus buiit returns nothing. The suggest.cfq parameter seems to be filtering out common names, despite https://bie-ws.ala.org.au/ws/search/auto.json?q=platypus&idxType=TAXON being OK.

**Comment by vjrj** [comment]
We commented here:
https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1594054132079200
and some proposal for a fix in:
https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1595423577209600

**Comment by adam-collins** [comment]
Looks like a SOLR index change is required for https://github.com/AtlasOfLivingAustralia/ala-install, see the linked slack comments.
