### ISSUE TITLE
Remove ALS references in Config.groovy

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#28]
E.g.

```
biocache.solr.url = "http://index.als.scot/solr/"
defaultNameSourceAttribution = "National Species Lists"
commonNameSourceAttribution = "National Species Lists"
imageThumbnailUrl = "http://images.als.scot/image/proxyImageThumbnail?imageId="
imageLargeUrl = "http://images.als.scot/image/proxyImageThumbnailLarge?imageId="
imageSmallUrl = "http://images.als.scot/image/proxyImageThumbnailLarge?imageId="
```

We need to decide if we'll have "generic" values in `Config.groovy` or ALA-specific values...

**Comment by sbearcsiro** [comment]
@nickdos @charvolant @djtfmartin This ticket indicates `defaultNameSourceAttribution` and `commonNameSourceAttribution` should be removed - what about the `identifierSourceAttribution` and `synonymSourceAttribution` which share the same value?

**Comment by nickdos** [comment]
I meant that the ALS values should not be in the config.groovy - they should be in the ALS specific ansible script only. So the values should be changed to be either ALA specific or be generic.

**Comment by adam-collins** [comment]
appears done
