### ISSUE TITLE
Don't mess with search query - pass on "as is" to SOLR

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#29]
One of the problems with the old `bie-service` app was it tinkered with the search query (`q` param) which then made it impossible ~~to perform complex faceted queries or~~ for users to specify Boolean logic.

It looks like this has been copied over to the new version in the [SearchService.groovy](https://github.com/AtlasOfLivingAustralia/bie-index/blob/master/grails-app/services/au/org/ala/bie/SearchService.groovy#L92) file:

```
queryString = queryString +
                        "&q=" + URLEncoder.encode(
                        "commonNameExact:\"" + q + "\"^10000000000" +
                        " OR commonName:\"" + q.replaceAll(" ","") + "\"^100000" +
                        " OR commonName:\"" + q + "\"^100000" +
                        " OR rk_genus:\"" + q.capitalize() + "\"" +
                        " OR exact_text:\"" + q + "\"" +
                        " OR auto_text:\"" + q + "\"" +
                        " OR auto_text:\"" + q + "*\"" +
                        " OR text:\"" + q + "*\"",
                        "UTF-8")
```

I propose we use the move this logic into the `text` field in SOLR and provide boost options to help with relevance ranking. 

Related to issue #24.

**Comment by djtfmartin** [comment]
Agree this is better, but im not sure we'll be able to achieve the desired functionality with just boosts. We may need a plugin for SOLR.

**Comment by nickdos** [comment]
I've been playing with this bit of code - removing that block actually has little effect on the ordering of the results. 

I agree we'll probably need something more sophisticated than boosting... I'll investigate a bit more.

Do we have a test suite of queries?

**Comment by djtfmartin** [comment]
Not currently, but there maybe something we can pull from the old BIE for a test suite.

**Comment by nickdos** [comment]
from commit msg: Removed boosting - needs replacing with dismax field boosts or similar. Will be done for issue #24.
