### ISSUE TITLE
Include linkIdentifier in species data

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#299]
For some reason calls to the /species web service doesn't include the linkIdentifier https://bie-ws.ala.org.au/ws/species/https%3A//id.biodiversity.org.au/taxon/apni/51311124 it would be helpful to include this for external systems trying to track individual species.

**Comment by adam-collins** [comment]
Add `linkIdentifier` to the response model at https://github.com/AtlasOfLivingAustralia/bie-index/blob/master/grails-app/services/au/org/ala/bie/SearchService.groovy#L745
