### ISSUE TITLE
WP page links not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#302]
WP pages in the index are being displayed using the WP page ID, which no longer works in our current version of WP.

E.g. https://bie.ala.org.au/search?q=cite 

has

https://www.ala.org.au/?page_id=41019

that goes to WP home page instead of the expected 

https://www.ala.org.au/ala-logo-and-identity/

Fix is to index the full URL and show that in search results.

**Comment by matthewandrews** [comment]
Note that this should just work once the current [https://www.ala.org.au/sitemap.xml](https://www.ala.org.au/sitemap.xml) is indexed, as it contains URLs that work.

**Comment by charvolant** [comment]
Fixed in https://github.com/AtlasOfLivingAustralia/bie-index/releases/tag/v1.4.12
