### ISSUE TITLE
Update wordpress crawler for new sitemap.

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#311]
Wordpress now has multiple sources of site information, eg.

https://www-test.ala.org.au/sitemap-files/xml/posts/page/1/index.xml
https://www-test.ala.org.au/sitemap-files/xml/posts/post/1/index.xml

This will be needed before re-deploying the bie-index.

**Comment by adam-collins** [comment]
This is resolved by the use of the parent index https://www.ala.org.au/xmlsitemap.xml
