### ISSUE TITLE
Encoding of taxonIDs that are URLs

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#32]
APNI identifiers are now URLs eg. http://biodiversity.org.au/apc/2915713 These are not translated into LSIDs since they no longer resolve at http://lsid.tdwg.org

Using the URIs in bie-index causes a 404 error, since the URL becomes

http://bie-dev.ala.org.au/bie-index/taxon/http://biodiversity.org.au/apc/2915713

See https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/4

**Comment by charvolant** [comment]
Fixes in https://github.com/AtlasOfLivingAustralia/bie-plugin/pull/5 and https://github.com/AtlasOfLivingAustralia/bie-index/pull/38

**Comment by adam-collins** [comment]
This is no longer an issue.
