### ISSUE TITLE
Include "native", "endemic" & "introduced" attributes on taxa

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#326]
Names in the NSL appear to have values for "endemic" & "introduced" 

@elywallis said:
> we went digging around in the Australian Faunal Directory and found that there are flags in there for endemic in Australia and introduced. The 'endemic' flag is probably more restrictive than we really want but the 'introduced' flag looks to be a pretty decent list. Upshot is that we do actually have an authoritative source that we could draw from / are already drawing from that would allow us to start to include a 'native' flag on some species in BIE. 

@nielsklazenga said:
> APNI and APC tend to include only native taxa
> In Victoria, we have a deal with the department that VBA gets the establishment means (and degree of establishment) from VicFlora and VicFlora gets the conservation statuses from VBA

@nickdos said:
> I'm not sure all the fields for AFD that appear on the AFD site, come through in our data dump

@elywallis also suggested that we could get a CSV/Excel export of names and endemic/introduced status, that could be imported into a species list. That list could then be indexed and used to allow users to filter records on those attributes, as well as indexed in `bie-index` SOLR index.

**Comment by elywallis** [comment]
Just a note that in addition to "endemic" AFD also contains values:
* Known to occur in Australia
* Ubiquitous throughout Australia
* Known from type locality
These are probably less relevant for flagging native status but you can launch queries against them

**Comment by nielsklazenga** [comment]
I am not keen on a list that is to be maintained by ALA, or is not maintained at all. I expect nobody is. There is no easy solution for this issue.

Also, at least for plants, national values are of very limited use, as lots of taxa that are native to Australia are introduced in certain states and even taxa that are native to a state might be introduced in areas where they are not native. For example, [_Acacia dealbata_](https://biocache.ala.org.au/occurrences/search?taxa=Acacia+dealbata#tab_mapView) is native only to New South Wales, the Australian Capital Territory, Victoria and Tasmania. Occurrences in Western Australia, South Australia, Queensland and Norfolk Island are introduced.

I would really like the information to be available in ALA and the Establishment means (and Degree of establishment in future) facets to be a lot more useful. It will have to be at the state level, not national level though, and the information should be maintained by the states.

This is also something that should be able to be overridden on an occurrence basis and at least specimen data is often not the appropriate place to deliver this information, so we'd need to have more actionable annotations to make this really work.

**Comment by adam-collins** [comment]
This issue cannot progress without data. It has been a couple years and the data is still absent. Closing.
