### ISSUE TITLE
Names where nameComplete is not scientificName and scientificNameAuthorship

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#33]
Some complicated species do not simply have the authorship at the end of the name. For example, the names supplied by APNI have a scientificName, with correctly placed authorship information, canonicalName, the name you would use without authorship and scientificNameAuthor, which is what it says on the tin. As an example of a name that doesn't have the author tacked onto the end:

scientificName : Boronia coerulescens F.Muell. subsp. coerulescens

canonicalName: Boronia coerulescens subsp. coerulescens

scientificNameAuthorship: F.Muell.

The bie-index builds nameComplete from the scientificName and scientificNameAuthorship. If a nameComplete is supplied in the input data, it should use that in preference.

At the moment, `/taxon/$guid` provides the nameString of scientificName and author of scientificNameAuthor. The show.gsp view in bie-plugin formats these for the title. The search in bie-plugin uses nameComplete.

Formatting complicates things in show.gsp. show.gsp uses the bie:formatSciName tag, which italicises and otherwise mucks about, as appropriate. It handles phrase names using the PhraseNameParser. 

The APNI data provides a formatted version of the name for some names. For example, `Senna surattensis subsp. retusa (Vogel) Randell` is formatted as (inter-element spaces are important, but removed some someone can parse this):

```
<scientific>
  <name id='117622'>
    <scientific>
      <name id='117623'>
        <scientific>
          <name id='103256'>
            <element><i>Senna</i></element>
          </name></scientific>
          <element><i>surattensis</i></element>
       </name></scientific>
       <rank id='54410'>subsp.</rank>
       <element><i>retusa</i></element>
       <authors>
         (<base id='7535' title='Vogel, (J.R.)T.'>Vogel</base>) 
         <author id='8577' title='Randell, B.R.'>Randell</author>
       </authors>
  </name>
</scientific>
```

However, only APNI provides formatted names.

At the moment, scientificName, scientificNameAuthor and nameComplete will work just fine. Changing the terminology to nameComplete -> scientificName, scientificNameAuthor remains the same.

**Comment by charvolant** [comment]
Added nameComplete to bie-index and Talend OS processing of APNI.
I'm going to add another field, nameFormatted which contains an HTML formatted name, using `<span class="">` to mark the various components. This would allow the bie-plugin to just take the formatted name and use CSS to mark the spans properly.

**Comment by adam-collins** [comment]
I suppose this is done.
