### ISSUE TITLE
linkIdentifier should ignore synonyms if there is an accepted taxon

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#330]
For example Alectura lathami has no link identifier because there is a parent child synonym to Alectura lathami lathami.

In general, link identifiers are intended to provide an easy link to the most likely taxon. The import process should ignore oddities such as parent-child synonms.

**Comment by charvolant** [comment]
Also, while we're on that subject, a search for https://bie.ala.org.au/species/Alectura%2520lathami  returns results, which should not be happening.

**Comment by adam-collins** [comment]
Update the linkIdentifier process by adding a filter to excluded synonyms here  https://github.com/AtlasOfLivingAustralia/bie-index/blob/a73b3839422e44f341cb5832e6bbd79db2aabb45/grails-app/services/au/org/ala/bie/ImportService.groovy#L1602

**Comment by adam-collins** [comment]
Updating to set `linkIdentifier` for unique `taxonomicStatus:accepted`, otherwise for unique `taxonomicStatus:inferredAccepted`, and finally the current default behaviour.
