### ISSUE TITLE
Locate source of DOIs for publications

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#337]
Current source feeds do not include a DOI to original publications. See whether NSL, etc have that information available.

**Comment by adam-collins** [comment]
namePublishedInID (DOI) exists for some records but is not used in the UI. e.g. https://bie.ala.org.au/ws/species/https://biodiversity.org.au/afd/taxa/7ada1b0c-0204-4223-a3ad-7ebada55e87d

I wonder if it will be included in the UI/UX review.
