### ISSUE TITLE
Standardize exported field names: A plea for use of camelCase everywhere

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#34]
_From @Tasilee on August 19, 2014 13:11_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=668
_date:_ Tue May 13 18:54:15 2014
_author:_ leebel...@gmail.com

---

Using 

[http://bie.ala.org.au/ws/download?q=Macropus&fields=guid,kingdom,phylum,class,bioOrder,family,genus,nameComplete,scientificName,scientificNameRaw,scientificNameText,rank,occurrenceCount,georeferencedCount](http://bie.ala.org.au/ws/download?q=Macropus&fields=guid,kingdom,phylum,class,bioOrder,family,genus,nameComplete,scientificName,scientificNameRaw,scientificNameText,rank,occurrenceCount,georeferencedCount)

as an example, I noted that

nameComplete produces "Scientific Name" on export
scientificName produces "scientificName" on export
scientificNameRaw produces "Scientific Name" on export

So there is some ambiguity when looking at the output. I suspect there may be other fields with similar problems. 

Relating also to [issue #650](https://code.google.com/p/ala/issues/detail?id=650), it would be wonderful to see the exported field names as ALL camelCase as per ws. This would address the ambiguity problem. 

There is also (related to `#650`) the same issue of field definitions as (for example) [http://bie.ala.org.au/ws/admin/indexFields](http://bie.ala.org.au/ws/admin/indexFields) doesn't have a "Description" while happily [http://biocache.ala.org.au/ws/index/fields](http://biocache.ala.org.au/ws/index/fields) does.

_Copied from original issue: AtlasOfLivingAustralia/bie-webapp2#22_

**Comment by djtfmartin** [comment]
The current download service (which is pretty limited) has all camel case field headers.

**Comment by adam-collins** [comment]
appears done
