### ISSUE TITLE
List of vernacular names to avoid

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#340]
Some vernacular names are no longer acceptable in polite company. While the names themselves are data and should not be excluded, they should not appear as the headline common name for a species.

**Comment by charvolant** [comment]
Added deprecated common name status.
The bie-hub will have to ensure that it either uses the common name single or doesn't use deprecated names in the headline

**Comment by TaniaGLaity** [comment]
appears to be fixed
