### ISSUE TITLE
Bulk lookup of images

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#343]
Allow bulk lookup of images for applications such as the species list tool

**Comment by adam-collins** [comment]
This service is available and appears to be one of the services whose openapi documentation was lost in the migration from static file openapi config to annotation openapi config. 
https://github.com/AtlasOfLivingAustralia/bie-index/blob/a73b3839422e44f341cb5832e6bbd79db2aabb45/grails-app/controllers/au/org/ala/bie/SearchController.groovy#L165
https://github.com/AtlasOfLivingAustralia/bie-index/blob/a73b3839422e44f341cb5832e6bbd79db2aabb45/grails-app/controllers/au/org/ala/bie/SearchController.groovy#L196
https://github.com/AtlasOfLivingAustralia/bie-index/blob/a73b3839422e44f341cb5832e6bbd79db2aabb45/grails-app/controllers/au/org/ala/bie/SearchController.groovy#L330
