### ISSUE TITLE
Duplicate common names in header

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#346]
Eg. https://bie.ala.org.au/species/https://id.biodiversity.org.au/taxon/apni/51290421 has Dhani in Yuwaalayaay, Dhani in Yuwaalaraay, Dharraabiin in Yuwaalaraay, each duplicated

**Comment by charvolant** [comment]
Further investigation indicates that the upstream sources are providing multiple copies. In any case, reduce the extra copies.

**Comment by charvolant** [comment]
The import should also be showing Ribbon Gum and Manna Gum on the names tab. These do not seem to be appearing.

**Comment by TaniaGLaity** [comment]
appears to have been fixed
