### ISSUE TITLE
Grails4 and OIDC integration 

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/bie-index#349]
- Grails 4 migration

- Migrate application to the usage of OIDC as outlined in [this](https://confluence.csiro.au/pages/viewpage.action?pageId=1661624100) document.

**Comment by sughics** [comment]
OIDC changes Implemented under this [branch](https://github.com/AtlasOfLivingAustralia/bie-index/tree/feature/oidcIntegration2) with pull request #350 

Required ansible configs have been added under feature branches. (To merge after this app is ready to deploy with OIDC)

 - https://github.com/AtlasOfLivingAustralia/ansible-inventories/tree/feature/oidc-bie-index
 - https://github.com/AtlasOfLivingAustralia/ala-install/tree/feature/oidc-bie-index

**Comment by sughics** [comment]
Functional testing document linked below. It has been updated to include examples of wha the queries urls should look like. https://confluence.csiro.au/display/ALASD/BIE+Index+Test+Plan

**Comment by kylie-m** [comment]
Functional testing completed for all web services tests as per Confluence page.  All passed except images - not all links worked (some did). Results and notes here:  https://csiroau.sharepoint.com/:x:/r/sites/AtlasofLivingAustralia/Shared%20Documents/ALA%20-%20Systems/Testing/[BIE-index-test-16-aug-22.xlsx

(https://csiroau.sharepoint.com/:x:/r/sites/AtlasofLivingAustralia/Shared%20Documents/ALA%20-%20Systems/Testing/BIE-index-test-16-aug-22.xlsx?d=w4b0b03803f924c6cb910b73b2339c5d5&csf=1&web=1&e=V8Qjd4)?d=w4b0b03803f924c6cb910b73b2339c5d5&csf=1&web=1&e=V8Qjd4

**Comment by sughics** [comment]
IN Production
