### ISSUE TITLE
Add image voting

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#36]
See https://github.com/AtlasOfLivingAustralia/bie-webapp2/issues/1

Allow users to vote on a good representative image via a button.

**Comment by djtfmartin** [comment]
Im wondering if we can handle this by writing a separate micro service (with separate DB)  that just handles image ranking.

The bie-index doesn't have any proper persistence (no DB) and I'd have concerns about just using an index to store the rankings.

The other option is to add as an extension to image service to support this, but it would be good to keep the image-service agnostic to taxonomy.

**Comment by nickdos** [comment]
Just starting thinking about this too... I wonder if this is a good time to create a simple storage/persistence service for all sorts of kvp data across the ALA?

Possible use cases:
* image ranking
* common name ranking
* user settings in apps (e.g. biocache)
* user favourite/starred items in apps
* user dashboard page (general storage / prefs)
* persisting user preferences for ALA dashboard layout
* rewrite of species list app (pushing it)

Possible implementations:
* ecodata
* MongoDB app
* [CouchDB](http://www.couchdb.org/)

**Comment by nickdos** [comment]
Lets try storing votes in image-service.ala.org.au - as all images will have a record in here already.

**Comment by nickdos** [comment]
This was implemented in the images-client-plugin: https://github.com/AtlasOfLivingAustralia/images-client-plugin/search?q=voting&type=Commits
