### ISSUE TITLE
Admin Jobs not updated (404 looking for assets/sockets.js)

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/bie-index#364]
During imports under `/admin/` (using `1.8.2`) the jobs are not updated as in previous versions.

In the js console I see a 404 in https://especies-ws.gbif.es/assets/sockets.js
It seems that this resource is also missing in ALA:
https://bie-ws.ala.org.au/ws/assets/sockets.js

The js error:
![image](https://user-images.githubusercontent.com/180085/207123144-953c6535-de95-4a1d-be40-5c8dc3a41f04.png)

**Comment by vjrj** [comment]
BTW, in previous versions sockets.js is available.

**Comment by vjrj** [comment]
It sounds to me like the websocket plugin is not available in grails 4 and it was removed here:
https://github.com/AtlasOfLivingAustralia/bie-index/commit/25c95533b36a8b355eb0f90ec6a6bc0e596f1e1f

**Comment by adam-collins** [comment]
`SockJS` is used in both `_status.gsp` files. 

This looks like the import request for the now missing file `<asset:javascript src="sockets"/>`. This needs to be added to the admin page, e.g. https://bie-ws.ala.org.au/ws/admin
