### ISSUE TITLE
add admin tool for sitemap generation to bie-index

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/bie-index#374]

**Comment by adam-collins** [comment]
Refer to deprecated bie-service https://github.com/AtlasOfLivingAustralia/bie-service/blob/f0ede53563b79300a75499d3f96ceaf7ea6f9553/src/main/java/org/ala/web/admin/controller/CasSolrAdminController.java#L464

**Comment by adam-collins** [comment]
Feedback on these sitemap items please. 
- Taxonomic. Add accepted names to the sitemap.
   - `idxType:TAXON AND taxonomicStatus:accepted`
   - Exclude records with LSIDs not beginning with `http`. This is to exclude ALA generated identifiers.
   - Add to the sitemap these pages. They all resolve to an accepted taxon page.
     - `http://bie.ala.org.au/species/` + COMMON_NAME. This is only the preferred common name.
     - `http://bie.ala.org.au/species/` + NAME. Use the complete name if available.
- Wordpress pages. Sitemap already exists https://www.ala.org.au/xmlsitemap.xml
- Support pages. Sitemap not required as it is crawled https://support.ala.org.au/
- Collections. Add to sitemap.
  - `idxType:COLLECTION OR idxType:INSTITUTION OR idxType:DATAPROVIDER OR idxType:DATARESOURCE`
  - Add to sitemap `https://collections.ala.org.au/public/show/` + ID
- Gazetteer locations. URLs point at explore your area, `https://biocache.ala.org.au/explore/your-area#-17.7558|127.8768|12|ALL_SPECIES`. Location name information is not present on the linked page. Do not add to sitemap.
- Regions. URLs points to regions `https://regions.ala.org.au/feature/6205053#group=ALL_SPECIES&subgroup=&guid=&from=1850&to=2023&tab=speciesTab&fq=` Location information is present with title and map. Metadata for the area definition is not present. Species information on the page is pageable and incomplete. Do not add to sitemap.

**Comment by matthewandrews** [comment]
I noticed that, for the home site, we also have an old sitemap.xml file which has not been updated for a long time... I've now added a rewrite so that requests for sitemap.xml are rewritten to xmlsitemap.xml

**Comment by peggynewman** [comment]
I'll ask the taxonomy working group to have a look at this. I think that's a good set from the collectory, although there are a lot of rubbish data providers, I don't think we're ready to be rid of them yet.
@adam-collins what do you think about adding CAPAD areas?

**Comment by adam-collins** [comment]
CAPAD areas is included in `idxtype:REGION`, the Regions. I think more layer information should be included on the regions page but can continue without that.

**Comment by adam-collins** [comment]
collectory sitemap Pull request https://github.com/AtlasOfLivingAustralia/collectory/pull/218

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-bie-hub/pull/91 and https://github.com/AtlasOfLivingAustralia/bie-index/pull/375

**Comment by adam-collins** [comment]
Entry point to all sitemaps is `/sitemap.xml`
