### ISSUE TITLE
Duplicate SOLR conf dir in repo

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#40]
It's not clear why there are 2 SOLR conf directories in this repo:
- solr
- solr-prod

These both appear to be out of sync with the Ansible version, which makes 3 copies - which is a bit confusing. 

Should we remove these copies and point to Ansible version in README.md instead?

**Comment by djtfmartin** [comment]
yes we should do this.

**Comment by adam-collins** [comment]
resolved
