### ISSUE TITLE
Rationalise solr schema

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#45]
Go through the solr schema and provide one schema to rule them all with only the fields now actually used.

This needs to be placed in https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/solr/files/solr/bie/conf/schema.xml

Related: https://github.com/AtlasOfLivingAustralia/bie-index/issues/40

**Comment by charvolant** [comment]
Current list of fields identified in the bie-index code. Some rationalisation may be necessary.

acceptedConceptID
acceptedConceptName
acronym
additionalIdentifiers
australian_s
author
auto_text
categories
category_ACT_m_s
category_m_s
category_NSW_m_s
category_NT_m_s
category_QLD_m_s
category_SA_m_s
category_TAS_m_s
category_VIC_m_s
category_WA_m_s
commonName
commonNameDisplay
commonNameExact
commonNameSingle
conservationStatus
conservationStatus
conservationStatusACT
conservationStatusAUS
conservationStatusNSW
conservationStatusNT
conservationStatusQLD
conservationStatusSA
conservationStatusTAS
conservationStatusVIC
conservationStatusWA
content
dataProviderName
datasetName
description
distribution
establishmentMeans
exact_text
format
guid
hasChildren
id
idxtype
image
imageAvailable
imageCount
imageSource
institutionName
isAustralian
isExcluded
language
left
linkIdentifier
nameComplete
nameComplete
nameFormatted
namePublishedIn
namePublishedInID
namePublishedInYear
parentGuid
pestStatus
priority
rank
rankID
rankId
rawRank
regionType
right
rightsHolder
rk_*
rkid_*
scientificName
scientificNameAuthorship
scientificNameRaw
simpleText
source
speciesGroup
speciesSubgroup
status
subject
synonymDescription_s
synonymRelationship_s
taxonConceptID
taxonGuid
taxonomicStatus
taxonomicStatus
text
thumbnail

**Comment by charvolant** [comment]
Terms (fields) that are actually used in the index when everything is loaded

_version_
acceptedConceptID
acceptedConceptName
acronym
additionalIdentifiers
auto_name_exact
auto_text
auto_text_edge
categories
commonName
commonNameExact
concat_name
conservationStatusACT_s
conservationStatusAUS_s
conservationStatusNSW_s
conservationStatusNT_s
conservationStatusQLD_s
conservationStatusSA_s
conservationStatusTAS_s
conservationStatusVIC_s
conservationStatusWA_s
content
datasetID
datasetName
description
distribution
doc_name
establishmentMeans
exact_text
format
guid
id
idxtype
imageAvailable
language
license
linkIdentifier
name
nameComplete
nameFormatted
nomenclaturalStatus_s
parentGuid
rank
rankID
rights
rk_anamorph
rk_class
rk_cohort
rk_division
rk_division_zoology
rk_family
rk_form
rk_genus
rk_genus_group
rk_higher_taxon
rk_infraclass
rk_infrafamily
rk_infraorder
rk_order
rk_phylum
rk_section
rk_section_zoology
rk_species
rk_species_group
rk_subclass
rk_subdivision_zoology
rk_subfamily
rk_subgenus
rk_subkingdom
rk_suborder
rk_subphylum
rk_subsection_zoology
rk_subspecies
rk_subtribe
rk_superclass
rk_superfamily
rk_superorder
rk_supertribe
rk_tribe
rk_unknown
rk_variety
rkid_anamorph
rkid_class
rkid_cohort
rkid_division
rkid_division_zoology
rkid_family
rkid_form
rkid_genus
rkid_genus_group
rkid_higher_taxon
rkid_infraclass
rkid_infrafamily
rkid_infraorder
rkid_order
rkid_phylum
rkid_section
rkid_section_zoology
rkid_species
rkid_species_group
rkid_subclass
rkid_subdivision_zoology
rkid_subfamily
rkid_subgenus
rkid_subkingdom
rkid_suborder
rkid_subphylum
rkid_subsection_zoology
rkid_subspecies
rkid_subtribe
rkid_superclass
rkid_superfamily
rkid_superorder
rkid_supertribe
rkid_tribe
rkid_unknown
rkid_variety
scientificName
scientificNameAuthorship
scientificNameID_s
source
status
stopped_common_name
taxonConceptID
taxonGuid
taxonomicStatus
text
thumbnail

**Comment by charvolant** [comment]
Fields that we don't seem to use at the moment. Ones that should stay in anyway marked in **bold**

* acronym
* commonNameDisplay
* commonNameSingle
* commonNameSort
* conservationStatus (always added as conservationStatusXXX_s)
* dataProvider
* georeferencedCount
* institutionType
* name_complete In as nameComplete
* **namePublishedIn** This *should* be being used already

Things which should be added into the schema, because they're perfectly decent DwC terms

* nomenclaturalStatus
* scientificNameID
* **namePublishedInID** This *should* be being used already
* **namePublishedInYear** This *should* be being used already
* occurrenceCount
* otherGuid
* pestStatus
* priority
* **rightsHolder** (dcterm that should stay in for description of odd bits of data)
* **speciesGroup** (to be added)
* **speciesSubgroup** (to be added)
* **subject** (dcterm that should stay in for description of odd bits of data)
* synonym
* uid - possibly used instead of guid
* url - should be something more specific, such as source

**Comment by charvolant** [comment]
Fields that are in the code, just not in a loading path at the moment:

* occurrenceCount (SearchService)
* conservationStatus (SearchService)
* pestStatus (SearchTaxonConcepotDTO)

SolrSearchService seems to have a large number of fields that never get added anywhere:

* acceptedConceptName
* synonymRelationship_s
* synonymDescription_s
* commonNameDisplay
* commonNameSingle
* imageSource
* imageCount
* left
* right
* author
* australian_s
* is_excluded_b
* pestStatus
* conservationStatus
* simpleText
* institutionName
* regionTypeName
* dataProviderName
* conservationStatusXXX (no _s suffix)
* bioOrder
* linkIdentifier

**Comment by nickdos** [comment]
occurrenceCount to stay in - see #54 which I've just completed.

**Comment by charvolant** [comment]
Does the occurrenceCount go into the solr index? It looks like it's added from the biocache during retrieval?

**Comment by nickdos** [comment]
Yes that's right - but it may go in the index in the future?

**Comment by charvolant** [comment]
In it goes.

**Comment by charvolant** [comment]
The only thing that uses the `SolrSearchService` is `speciesLookupBulk` connected to `/species/lookup/bulk` does anything use this at the moment? Outside the bie-index, it's only mentioned in https://github.com/AtlasOfLivingAustralia/ALA4R/blob/master/R/cached_post.R as far as I can see

**Comment by adam-collins** [comment]
old
