### ISSUE TITLE
Document names indexing process

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#47]
Would be good to have a Wiki page on how we process the names (AFD & APNI) in general terms and how it relates to biocache records, etc. This would be for an external audience so they can understand the "sausage machine" part that the ALA does, as opposed to what the Dept Env provides, etc.

**Comment by charvolant** [comment]
Documentation is at https://github.com/AtlasOfLivingAustralia/bie-index/blob/master/doc/nameology/index.md

Is there a way of automatically syncing this with the wiki page?

**Comment by nickdos** [comment]
This looks like a solution:

http://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/

**Comment by adam-collins** [comment]
appears done
