### ISSUE TITLE
Index list tool for conservation lists

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/bie-index#5]
Index the lists accessible via the services:
- Sensitive lists: http://lists.ala.org.au/ws/speciesList?isSDS=eq:true
- Conservation lists: http://lists.ala.org.au/ws/speciesList?isThreatened=eq:true
- Authoritative lists: http://lists.ala.org.au/ws/speciesList?isAuthoritative=eq:true

**Comment by nickdos** [comment]
See http://bie.ala.org.au/search?q=robin&fq=speciesGroup:Birds

**Comment by adam-collins** [comment]
All done, except for SDS lists, although the `include in BIE` flag can be set to include a specific list in the BIE. Also, this has been brought up more recently and elsewhere.
