### ISSUE TITLE
Handle accented characters in names gracefully

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#51]
Scientific names _should_ only use un-accented characters. However, historically, this hasn't always been the case and we end up with names such as _Aleochara haemorrhoïdalis_ (note the umlauted i). Searching for _Aleochara haemorrhoidalis_ should also match this name, as should weird capitalisations.

**Comment by charvolant** [comment]
A query of $BASE/bie-index/search?q=Aleochara+haemorrhoidalis or q=Aleochara+haemorrho%C3%AFdalis returns *Aleochara (Aleochara) actae* as the first result. As does the full bie-index query http://localhost:8983/solr/bie/select?q=Aleochara+haemorrhoidalis&qf=doc_name^100+text&bq=taxonomicStatus:accepted^1000+rankID:7000^1000&defType=edismax&q.alt=text:*&hl=true&hl=true&hl.fl=*&hl.simple.pre=%3Cb%3E&hl.simple.post=%3C/b%3E&wt=json&facet=false&facet.mincount=1

http://localhost:8983/solr/bie/select?q=doc_name:%22Aleochara%20haemorrhoidalis%22&qf=doc_name^100+text&bq=taxonomicStatus:accepted^1000+rankID:7000^1000&defType=edismax&q.alt=text:*&hl=true&hl=true&hl.fl=* returns *Aleochara haemorrhoïdalis" as the first response

http://localhost:8983/solr/bie/select?q=doc_name:Aleochara+haemorrhoidalis&qf=doc_name^100+text&bq=taxonomicStatus:accepted^1000+rankID:7000^1000&defType=edismax&q.alt=text:*&hl=true&hl=true&hl.fl=* returns *Pseudolycus haemorrhoidalis*

**Comment by adam-collins** [comment]
Something added so I guess this is done.
