### ISSUE TITLE
Lifeform (species group) indexing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#52]
_From @nickdos on March 29, 2016 3:50_

Old BIE has a facet for Lifeform (species groups) and species subgroups.

Currently BIE has acopy of the subgroups.json file hosted on apache static page served under:

http://bie.ala.org.au/ws/subgroups.json

We need to serve this from the new bie-index (or move it over to biocache-service) and then use this lookup when indexing taxa.

Tasks:
- [x] host subgroups.json 
- [x] read subgroups.json (cached)
- [x] when indexing taxa, add lookup for the higher taxa against each group/subgroup and add data field in SOLR doc (for accepted taxa only?)

_Copied from original issue: AtlasOfLivingAustralia/bie-plugin#12_

**Comment by adam-collins** [comment]
Available at https://biocache.ala.org.au/ws/explore/hierarchy
