### ISSUE TITLE
Implement "recorded in Australia" facet

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#53]
This will require someone to look at old BIE indexing code to see how it works. Current web service has `isAustralian: "recorded"` indexed.

**Comment by nickdos** [comment]
Some note...
found reference in bie-profile - AustralianTaxonLoader.java line 83:

```
if(austLsidPattern.matcher(guid).matches())
    isAust = true;
else{
    if(scanner.getCurrentValues().get("hasGeoReferencedRecords") != null){
        Object[] resp = restfulClient.restGet(WS_URL+guid);
        if((Integer)resp[0] == HttpStatus.SC_OK){
            String content = resp[1].toString();
            if(content != null && content.length()>3){
                AustralianDTO adto = mapper.readValue(content, AustralianDTO.class);
                if(adto != null)
                    isAust = adto.getIsAustralian();
            }
        }
    }
}

with the pattern being `Pattern.compile("urn:lsid:biodiversity.org.au[a-zA-Z0-9\\.:-]*")`

so all names from ANBG are included and then any other names are searched against the biocache.
```

**Comment by nickdos** [comment]
Made a change in biocache-service which is a dependency for this issue:

https://github.com/AtlasOfLivingAustralia/biocache-service/commit/6b1dba7454b5110cfb9f59067c8f16e6f1c3502e

**Comment by nickdos** [comment]
Doug suggests using the dataset_id as a key to identify the Australian sourced names (via a config var), as a replacement for the ugly regex.

**Comment by adam-collins** [comment]
Work was done. Closing.
