### ISSUE TITLE
Implement occurrence record count

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#54]
For each taxa, add a SOLR field for the number of occurrences in biocache. Current BIE uses a field called `occCount`. 

This is probably a dependency on issue #53

**Comment by nickdos** [comment]
@djtfmartin says these counts are out of date in current prod index. Results page uses ajax to lookup counts. Investigate if we still need this feature.

**Comment by djtfmartin** [comment]
this is done as far as I can see
https://github.com/AtlasOfLivingAustralia/bie-index/commit/612242ecba2d848d464c2bd102077408d232623e
