### ISSUE TITLE
Indexing of images (not working)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#55]
There is code to index images but current test version has no image data indexed!

Work out why we're not getting any image data and fix it.

Then test ala-bie (bie-plugin) to see if the image thumbnails are appearing in the search results list.

**Comment by nickdos** [comment]
@djtfmartin says code currently is calling biocache SOLR directly. Suggest we call biocache web service instead.

**Comment by pwscsiro** [comment]
Refactored indexImages() (looks like a verb but seems to be a noun in this case - that is this method retrieves the index Images, doesn't index the images) to retrieveImageDetailsForIndexing(). Not sure how it knows what images to retrieve.

**Comment by pwscsiro** [comment]
Possible sequence: 
![indeximages](https://cloud.githubusercontent.com/assets/17239936/14306300/1cf724bc-fc09-11e5-8d44-ca08564ebf48.png)

**Comment by pwscsiro** [comment]
Existing Solr query example:
http://bie-dev.ala.org.au/solr/biocache/select?q=*%3A*&fq=multimedia%3AImage&fl=taxon_name%2C+image_url%2C+data_resource_uid&wt=csv&indent=true&rows=100000
(repeated replacing taxon_name with each value in ["taxon_name", "genus", "family", "order", "class", "phylum"]

**Comment by nickdos** [comment]
Example biocache service calls:

http://biocache.ala.org.au/ws/occurrences/search.json?q=multimedia:Image&fq=rank_id:[7000+TO+*]&facet=off&start=0&pageSize=10

http://biocache.ala.org.au/ws/occurrences/search.json?q=multimedia:Image&fq=rank_id:[5000+TO+6999]&facet=off&start=0&pageSize=10

so repeat with ranges of `rankId`
`1000 == kingdom` and `7000 == species`

**Comment by nickdos** [comment]
I can see why @djtfmartin used the SOLR query - it only passes back the 3 fields and in CSV format so saves a lot bandwidth in the call. Maybe first version should be to keep Dave's code and simply point at the "backup" biocache SOLR instance (which is currently prod due to server outage with ala-rufus).

http://ala-cohen.it.csiro.au:8080/solr/#/biocache/query

**Comment by djtfmartin** [comment]
Thanks @pwscsiro and @nickdos. 

I was actually thinking we need a wrapper service in biocache-service for this SOLR call (so we arent interacting with biocache SOLR directly from bie-index).

**Comment by pwscsiro** [comment]
Turns out this was related to the SOLR url config, not the code base. Closing.
