### ISSUE TITLE
webservice: maintain order of requested facets in facetResults

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#56]
Given the URL: http://bie-dev.ala.org.au/bie-index/search?q=*:*&start=0&rows=0&sort=&dir=asc&facets=idxtype,rank,imageAvailable,speciesGroup,conservationStatusAUS_s,conservationStatusACT_s,conservationStatusNSW_s,conservationStatusQLD_s,conservationStatusVIC_s,conservationStatusTAS_s,conservationStatusSA_s,conservationStatusWA_s,conservationStatusNT_s

Current behaviour: `facetResults` JSON comes back in alphabetical order. 
Required behaviour: `facetResults` JSON to be in the order specified in `facets` param.

**Comment by nickdos** [comment]
Duplicate of #57

**Comment by adam-collins** [comment]
appears done
