### ISSUE TITLE
Specify the order of facets in faces list

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#57]
_From @nickdos on March 29, 2016 3:42_

Conservation status facets are appearing before "Section", etc. We need to be able to specify the order the facet appear in. 

_Copied from original issue: AtlasOfLivingAustralia/bie-plugin#11_

**Comment by nickdos** [comment]
This is a `bie-index` issue, so moving...

**Comment by adam-collins** [comment]
Cannot identify what is outstanding
