### ISSUE TITLE
Handle misspelled taxon names (fuzzy matching)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#62]
Some example names provided by a user:
- Hedycarya loxocarpa – should  be Hedycarya loxocar**y**a
- Pseuderanthemum variab**l**e – should  be Pseuderanthemum variabile
- Pullea st**r**utzeri – should  be Pullea stutzeri
- Rubus muluccanus – should  be Rubus m**o**luccanus

These should show the correct name (on the right) as the top hit. Current (old) version fails miserably at this.

**Comment by charvolant** [comment]
ala-name-matching has a soundex class that should catch these but it requires the index to be pre-populated. It sounds like we need to start using ala-name-matching in the bie-index.

**Comment by nickdos** [comment]
Searched high and low for "global" way of handling this in SOLR and there isn't one. So I "augmented" the search terms by adding a trailing `~`. Works well for the examples above.

**Comment by adam-collins** [comment]
Appears working. Expected match appears 1st, or 2nd after the genus match.
