### ISSUE TITLE
Add admin function to swap SOLR cores

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#66]
We will likely place SOLR behind a firewall in prod, so it would be good to trigger the core swap via webservice using an admin widget. Would be good to see which core is loaded with which directory as well (e.g. provide similar feedback that SOLR admin provides), if SOLR web services allows it.

![image](https://cloud.githubusercontent.com/assets/532845/15036358/099c0d54-12d1-11e6-8a20-b7f8ae3e0f09.png)

**Comment by adam-collins** [comment]
done
