### ISSUE TITLE
http://bie.ala.org.au/ws/admin/indexFields appears to need authentication

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/bie-index#77]
http://bie.ala.org.au/ws/admin/indexFields now appears to require authentication - was this intentional? This has broken significant parts of ALA4R.

**Comment by nickdos** [comment]
`admin` portion of URL means it should be under authentication but this page should be public. So URL path needs changing to remove the `admin` part. I'll put a redirect in place and serve it with a `public` path and update http://api.ala.org.au/.
