### ISSUE TITLE
Conservation status on species pages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#78]
User has reported the conservation status label on species pages have the following issues:
e.g. http://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2892061
- link to the `dr652` page is 404 
- text label is `Least concern wildlife` which some people think is only for animals (QLD uses this term however. Maybe we should use the EPBC term instead?
- formatting of label has words running together - `QLDLeast concern wildlife` - presumably if the icon is not displaying properly for QLD (test in IE) - see attachment below.

![ala conservation status peculiar](https://cloud.githubusercontent.com/assets/532845/17087278/d86a2424-5249-11e6-868b-a215c243548b.png)

**Comment by nickdos** [comment]
I think this is an indexing issue as the conservation status facets for QLD are different to the other states. See this screenshot:

![acacia___search](https://cloud.githubusercontent.com/assets/532845/17092419/e3cc074c-5285-11e6-9490-f6a80461cbc5.png)

All other states use the EPBC terms except QLD.

**Comment by adam-collins** [comment]
Handled elsewhere. Cannot find the link.
