### ISSUE TITLE
Document JSON structure changes in new API

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#83]
A user has asked for a list of changes to the new API compared with the old API - I think we should do this. The old api is running on a different DNS entry (ala-bie1.vm.csiro.au - but check with Matt). 

Use a few plant and animal names as reference and put together a doc or spreadsheet (don't care on format) that shows changes in both input params (if any) and output JSON format.

So it should apply to these end points:
- `/search.json`
- `/species/{guid}.json`
- `/admin/indexFields` - needs fixing to remove admin as its under AUTH
- `species/lookup/bulk`
- `/download`
- `/guid/batch.json`
- `/classification/{guid}`

**Comment by sbearcsiro** [comment]
Generated diffs (JSON and generic) that have been augmented with prose visible at: https://sbearcsiro.github.io/bie-api-changes/

Update by following README in https://github.com/sbearcsiro/bie-api-changes

**Comment by adam-collins** [comment]
old
