### ISSUE TITLE
bull ant species thinks it's a plant

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/bie-index#85]
http://bie.ala.org.au/species/ALA_Myrmecia_sp._17

actual occurrence records are here: http://biocache.ala.org.au/occurrences/search?q=taxon_name%3A%22Myrmecia+sp.+17%22 

the record on the species page are for grevillia sp.

**Comment by nickdos** [comment]
BIE index was updated and L&R values changed - fixed by reverting to previous index.
