### ISSUE TITLE
Kingdom level taxa have null `kingdom` values

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#97]
E.g. Fungi - http://bie.ala.org.au/ws/search.json?q=fungi&fq=rank:kingdom

`kingdom: null,`

which means users can't search for `kingdom:fungi`...

This seems to be a pattern for all higher taxa, where the current rank is not populated for that taxon - only its higher taxa.

See Ben's email with more details:

> Similarly, http://bie.ala.org.au/ws/search.json?q=Fungi confirms that Fungi is a valid kingdom.
> Yet none of these seem to return a match:
> 
> http://bie.ala.org.au/ws/search.json?q=rkid_kingdom%3AFungi
> http://bie.ala.org.au/ws/search.json?q=kingdom%3AFungi
> http://bie.ala.org.au/ws/search.json?fq=rkid_kingdom%3AFungi
> http://bie.ala.org.au/ws/search.json?fq=kingdom%3AFungi

**Comment by charvolant** [comment]
For the name, the search should be rk_kingdom:Fungi not rkid_kingdom:Fungi rkid_XXX is for the taxon guid

http://bie.ala.org.au/ws/search.json?fq=rk_kingdom:Fungi
http://bie.ala.org.au/ws/search.json?fq=rkid_kingdom:%22urn:lsid:indexfungorum.org:names:90156%22

**Comment by adam-collins** [comment]
Appears working
