### ISSUE TITLE
Higher taxa fields confusion

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#98]
The old BIE had simple field names for higher taxa like `kingdom`. The new BIE uses `rk_kingdom` and `rkid_kingdom` - not clear what the difference is. Furthermore, the search results return `kingdom:ANIMALIA` in the JSON but users can't search or filter on these values, as they're different to the actual indexed field (= not RESTful). 

Also related to https://github.com/AtlasOfLivingAustralia/bie-index/issues/97

Email from Ben:

> 3.The resolution between the old taxonomic field names (kingdom, phylum, etc) and the new ones (rkid_kingdom, etc) still isn't clear:
> 
> http://bie.ala.org.au/ws/search.json?q=oenanthe&fq=rank%3Agenus&sort=kingdom
> 
> returns an error:
> 
> `{"error":"Server returned HTTP response code: 400 for URL: 
>     http://biocache-aws.ala.org.au:8080/solr/bie/select?q=oenanthe&qf=exact_text^200+doc_name^100+text&bq=taxonomicStatus:accepted^2000&bq=rankID:7000^500&bq=rankID:6000^100&bq=scientificName:(*+-\"*+x+*\")^500&bq=taxonomicStatus:(*+-misapplied+-excluded+-\"miscellaneous+literature\")^1000&defType=edismax&q.alt=text:*&hl=true&hl=true&hl.fl=*&hl.simple.pre=<b>&hl.simple.post=<\u002fb>&wt=json&facet=false&facet.mincount=1&start=0&rows=10&sort=kingdom%20asc&fq=rank%3Agenus","indexServer":"http://biocache-aws.ala.org.au:8080/solr/bie"}`
> 
> Replacing "kingdom" with "rkid_kingdom" works and returns (I think) the expected result.
> 
> Replacing "genus" with "rkid_genus" (i.e.  http://bie.ala.org.au/ws/search.json?q=oenanthe&fq=rank%3Arkid_genus&sort=rkid_kingdom)  works (does not throw an error) but returns an empty result set.
> 
> 4.Related to that, the fields list http://bie.ala.org.au/ws/admin/indexFields returns the rkid_\* form of  the field names.

**Comment by adam-collins** [comment]
No need to support old BIE anymore
